LPP-51452 portal-search-elasticsearch7: Add log info to Elasticsearch connection manager
liferay-search/liferay-portal pull request #1186
Opened 2023-12-12 21:18 UTC by gustavolimav

2023-12-12 21:18 UTC, liferay-continuous-integration commented
The following guidelines have been set by the owner of this repository: 
- &nbsp;&nbsp;&nbsp;&nbsp;"Thank you for sending this PR to liferay-search! If you haven't already, take this opportunity to review our [pull request guidelines](https://liferay.atlassian.net/l/cp/MmMP1Sh0). For additional help, reach out via the appropriate channels listed [here](https://liferay.atlassian.net/l/cp/MmMP1Sh0#Communication%2C-point-of-contact)."

2023-12-12 21:18 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2023-12-12 21:26 UTC, gustavolimav commented
Hi @joshuacords,

Today I added log messages to the functions responsible for updating the Elasticsearch settings, to the classes that manage the connection to Elasticsearch and to the class responsible for displaying the connection information. Could you review this initial PR when you get a chance? Your feedback would be very helpful. 

I'll take a look at it again tomorrow. I only had time to add these logs today. Thanks!

2023-12-13 01:22 UTC, joshuacords commented on modules/apps/portal-search-elasticsearch7/portal-search-elasticsearch7-impl/src/main/java/com/liferay/portal/search/elasticsearch7/internal/configuration/ElasticsearchConfigurationWrapper.java
> +			_log.info("Start Update Elasticsearch Configuration");
Let's log what the configuration is.

2023-12-13 01:22 UTC, joshuacords commented on modules/apps/portal-search-elasticsearch7/portal-search-elasticsearch7-impl/src/main/java/com/liferay/portal/search/elasticsearch7/internal/connection/ElasticsearchConnectionManager.java
> +			_log.info("Start Adding Elasticsearch Connection");
Log what the configuration is.

2023-12-13 01:27 UTC, joshuacords commented on modules/apps/portal-search-elasticsearch7/portal-search-elasticsearch7-impl/src/main/java/com/liferay/portal/search/elasticsearch7/internal/connection/ElasticsearchConnectionManager.java
>  		}
Could we log what the _elasticsearchConnectionSupplier returns and if it's null.

2023-12-13 01:30 UTC, joshuacords commented on modules/apps/portal-search-elasticsearch7/portal-search-elasticsearch7-impl/src/main/java/com/liferay/portal/search/elasticsearch7/internal/connection/ElasticsearchConnectionManager.java
> +			String remoteClusterConnectionId =
Could we log what the remoteClusterConnectionId is.

2023-12-13 01:33 UTC, joshuacords commented on modules/apps/portal-search-elasticsearch7/portal-search-elasticsearch7-impl/src/main/java/com/liferay/portal/search/elasticsearch7/internal/information/ElasticsearchSearchEngineInformation.java
> +					elasticsearchConnection.getConnectionId());
Log everything in connection id, especially the name.

2023-12-13 01:33 UTC, joshuacords commented on modules/apps/portal-search-elasticsearch7/portal-search-elasticsearch7-impl/src/main/java/com/liferay/portal/search/elasticsearch7/internal/information/ElasticsearchSearchEngineInformation.java
>  			return;
Log if null

2023-12-13 01:35 UTC, joshuacords commented on modules/apps/portal-search-elasticsearch7/portal-search-elasticsearch7-impl/src/main/java/com/liferay/portal/search/elasticsearch7/internal/information/ElasticsearchSearchEngineInformation.java
>  		}
What are these labels? If they are related to the connection names we should log them.

2023-12-13 01:36 UTC, joshuacords commented on modules/apps/portal-search-elasticsearch7/portal-search-elasticsearch7-impl/src/main/java/com/liferay/portal/search/elasticsearch7/internal/information/ElasticsearchSearchEngineInformation.java
>  			filterString);
Where ever connectionInformationList is being passed from, we should have logging on that.

2023-12-13 01:39 UTC, joshuacords commented
Good start Gustavo. As a mindset, we don't care how busy a debug patch logs are, we just want to make sure we capture anything that could be important that way we only need the customer to use it once. (That said, it's likely some of what I requested is redundant, but it's hard to tell without testing it.)

As you add to this, a comment with what output looks like could be helpful.

Thank you

2023-12-13 17:35 UTC, joshuacords requested changes
Take a look at these suggestions.

2023-12-13 21:51 UTC, closed without merging