LPD-15357 Create test coverage reindex own instance
liferay-search/liferay-portal pull request #1258
Opened 2024-02-05 20:22 UTC by gustavolimav

I had convert the unit tests to integration tests following this request from Bchan https://github.com/brianchandotcom/liferay-portal/pull/146849

2024-02-06 21:56 UTC, joshuacords requested changes
Our portal-search-admin-web modules already has tests within it, so I don't see a need to create a new portal-search-admin-web-test. Could you move these test into the existing module under a testIntegration folder? (See journal-test which has both unit and integration tests)

2024-02-07 11:50 UTC, gustavolimav commented
Hi @joshuacords, I haven't found any example of a web module that has integration tests inside it. I'm following the pattern I found in the Liferay code, I haven't found a reason why it's like that, but I figured it had a reason. Do you have any example of that?

As I explained in the PR that wasn't related to this story, the user can't have access to this class if they can't have access to the search portlet in the control panel, so the Feature flag here is unnecessary, without the feature flag only omniadmins will have access to the search portlet in contral panel, with the feature flag maybe some company admins will have access. In general, I don't think adding the resource flag to this class makes sense. The only reason I see is to test the actual behavior and the behavior we're adding in this story. I can see benefits in having it explicit in the code and in the test. I can add it, it's not a big deal, just to make it clear that the absence of the feature flag is not a problem in terms of functionality.

And @lipusz, could you please don't close the PR before we conclude the conversation? I could still continue pushing code here instead of open a new one, I can't see benefit in close it.

2024-02-07 19:07 UTC, joshuacords commented
Hi @xbrianlee,
Could you look at the last 2 comments of this PR where we discuss the location of tests in modules. Would you happen to know if there's a liferay standard to follow?

2024-02-07 19:16 UTC, xbrianlee commented
@joshuacords Unfortunately I'm not familiar with any criteria for the location of tests in modules. If I can use functional test organization as a proxy, I'd say there are likely multiple standards that teams follow. Every other year or so tests get reorganized as new features and modules get added.

2024-02-07 20:51 UTC, joshuacords commented
> As I explained in the PR that wasn't related to this story, the user can't have access to this class if they can't have access to the search portlet in the control panel, so the Feature flag here is unnecessary, without the feature flag disabled only omniadmins will have access to the search portlet in contral panel, with the feature flag enabled maybe some company admins will have access depending on the configuration. In general, I don't think adding the feature flag to this class makes sense. The only reason I see is to test the actual behavior and the behavior we're adding in this story. I can see benefits in having it explicit in the code and in the test. I can add it, it's not a big deal, just to make it clear that the absence of the feature flag is not a problem in terms of functionality.

I manually tested this to confirm - a feature flag check isn't necessary in the class or in the test because access is already blocked by the portal.

2024-02-07 21:06 UTC, joshuacords commented
I tried running the integration tests, both with and without the feature flag enabled, and it's failing:

> com.liferay.portal.search.admin.web.internal.portlet.action.test.EditMVCActionCommandTest STANDARD_OUT
>     Loading jar:file:/home/me/dev/bundles/LPD-6591-2/tomcat-9.0.83/webapps/ROOT/WEB-INF/shielded-container-lib/portal-impl.jar!/system.properties
>     Loading jar:file:/home/me/dev/projects/liferay-portal/.m2/com/liferay/portal/com.liferay.portal.impl/98.2.0-SNAPSHOT/com.liferay.portal.impl-98.2.0-SNAPSHOT.jar!/system.properties
> 
> com.liferay.portal.search.admin.web.internal.portlet.action.test.EditMVCActionCommandTest > classMethod STARTED
> 
> com.liferay.portal.search.admin.web.internal.portlet.action.test.EditMVCActionCommandTest > classMethod FAILED
>     java.net.ConnectException: Connection refused (Connection refused)
>         at java.net.PlainSocketImpl.socketConnect(Native Method)
>         at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
>         at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
>         at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
>         at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
>         at java.net.Socket.connect(Socket.java:589)
>         at java.net.Socket.connect(Socket.java:538)
>         at java.net.Socket.<init>(Socket.java:434)
>         at java.net.Socket.<init>(Socket.java:244)
>         at com.liferay.arquillian.extension.junit.bridge.client.FrameworkState.connect(FrameworkState.java:53)
>         at com.liferay.arquillian.extension.junit.bridge.client.ClientState.open(ClientState.java:67)
>         at com.liferay.arquillian.extension.junit.bridge.junit.Arquillian.run(Arquillian.java:111)
>         at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:110)
>         at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
>         at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
>         at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62)
>         at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
>         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>         at java.lang.reflect.Method.invoke(Method.java:498)
>         at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
>         at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
>         at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
>         at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
>         at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
>         at org.gradle.api.internal.tasks.testing.worker.TestWorker$2.run(TestWorker.java:176)
>         at org.gradle.api.internal.tasks.testing.worker.TestWorker.executeAndMaintainThreadName(TestWorker.java:129)
>         at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:100)
>         at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:60)
>         at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:56)
>         at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:133)
>         at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:71)
>         at worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
>         at worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)
> 
> 1 test completed, 1 failed
> 

@gustavolimav - do you know what the issue may be?

2024-02-07 22:15 UTC, joshuacords commented
It appears that the test runs fine when a portal is not running, but I can't get it to run successfully on an already running portal.

2024-02-07 23:07 UTC, joshuacords commented
Hi @gustavolimav, sorry for the confusion, besides removing the lines from the build.gradle, this looks good to forward. 

We'll see if B.Chan likes the new module. In the abstract it does seem better to me to keep testing in separate modules where possible to reduce the size of what we're delivering so we'll go with your approach.

2024-02-08 11:46 UTC, gustavolimav commented
@joshuacords, what you mean with build.gradle lines? did you submit any review?

2024-02-08 17:32 UTC, joshuacords requested changes

2024-02-08 17:36 UTC, joshuacords commented on modules/apps/portal-search/portal-search-admin-web-test/bnd.bnd
> +Bundle-SymbolicName: com.liferay.portal.search.admin.web.test
Test Comment

2024-02-08 17:42 UTC, gustavolimav commented
ci:test:sf

2024-02-08 17:44 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-25.liferay.com/job/test-portal-source-format/2504/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/2504/jenkins-report.html">here</a>.</b></p>

2024-02-08 17:46 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/53401963f02f593bbf555b4b321fdaeb59e03a53">53401963f02f593bbf555b4b321fdaeb59e03a53</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/gustavolimav/liferay-portal/tree/2024_01_25_TEST_LPD-15357_Create_Test_Coverage_reindex_own_instance">2024_01_25_TEST_LPD-15357_Create_Test_Coverage_reindex_own_instance</a><br/>Branch GIT ID: <a href="https://github.com/gustavolimav/liferay-portal/commit/3b331055bda5b1a85e6a764b910fa92d113573aa">3b331055bda5b1a85e6a764b910fa92d113573aa</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-25.liferay.com/job/test-portal-source-format/2504/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/2504/jenkins-report.html">here</a>.</h5></details></html>

2024-02-08 17:49 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-25.liferay.com/job/test-portal-source-format/2504/">test-portal-source-format#2504</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/2504/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-search/liferay-portal/pull/1258">liferay-search#1258</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2536578980">[master] ci:test:sf - gustavolimav &gt; liferay-search - PR#1258 - 2024-02-08[09:42:39]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>2536578980<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-25.liferay.com/job/publish-testray-report/9903/">publish-testray-report#9903</a><br/></div></div>

2024-02-08 18:16 UTC, gustavolimav commented
ci:test:search

2024-02-08 18:16 UTC, gustavolimav commented
ci:test:relevant

2024-02-08 18:43 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>search</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest(master)/3609/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/3609/jenkins-report.html">here</a>.</b></p>

2024-02-08 18:44 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest(master)/3610/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/3610/jenkins-report.html">here</a>.</b></p>

2024-02-08 21:14 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:stable - 31 out of 32 jobs passed</h3><h3>:x: ci:test:relevant - 75 out of 80 jobs passed in 2 hours 31 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/7d2acf9f5135c7e3e5d6fcead88cfd2e9e5f19be">7d2acf9f5135c7e3e5d6fcead88cfd2e9e5f19be</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/e5cd9b9d7fb5332ad7593caa307e433a35796070">e5cd9b9d7fb5332ad7593caa307e433a35796070</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2535608297">EE Development Acceptance (master) - 350 - 2024-02-06[08:41:44]</a></p><details><summary><strong>ci:test:stable - 31 out of 32 jobs PASSED</strong></summary><div><h4>1 Failed Jobs:</h4><ul><li>build-iw-jdk8<ul><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/751711/">build-iw-jdk8/0/0</a></li></ul></li><li>central-requirements-jdk8<ul><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/910596/">central-requirements-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57-jdk8_stable<ul><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/836459/">functional-smoke-tomcat90-mysql57-jdk8_stable/0/0</a></li></ul></li><li>functional-upgrade-tomcat90-mysql57-jdk8_stable<ul><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/836458/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/0</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1026225/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/1</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/833512/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/2</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1027672/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/3</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/844907/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/4</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/554544/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/5</a></li></ul></li><li>js-unit-jdk8<ul><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/798273/">js-unit-jdk8/0/0</a></li></ul></li><li>modules-compile-jdk8<ul><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1026223/">modules-compile-jdk8/0/0</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/751712/">modules-compile-jdk8/0/1</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/833510/">modules-compile-jdk8/0/2</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/522068/">modules-compile-jdk8/0/3</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/751713/">modules-compile-jdk8/0/4</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/554543/">modules-compile-jdk8/0/5</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/522069/">modules-compile-jdk8/0/6</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/910593/">modules-compile-jdk8/0/7</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1026224/">modules-compile-jdk8/0/8</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/798272/">modules-compile-jdk8/0/9</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/798271/">modules-compile-jdk8/0/10</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1027670/">modules-compile-jdk8/0/11</a></li></ul></li><li>modules-integration-mysql57-jdk8_stable<ul><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/836461/">modules-integration-mysql57-jdk8_stable/0/0</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/751717/">modules-integration-mysql57-jdk8_stable/0/1</a></li></ul></li><li>modules-unit-jdk8_stable<ul><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/844910/">modules-unit-jdk8_stable/0/0</a></li></ul></li><li>playwright-js-tomcat90-mysql57-jdk8_stable<ul><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/836457/">playwright-js-tomcat90-mysql57-jdk8_stable/0/0</a></li></ul></li><li>pmd-jdk8<ul><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1027675/">pmd-jdk8/0/0</a></li></ul></li><li>portal-license-smoke-mysql57-jdk8<ul><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/554547/"><strike>portal-license-smoke-mysql57-jdk8/0/0</strike></a></li></ul></li><li>rest-builder-jdk8<ul><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/833514/">rest-builder-jdk8/0/0</a></li></ul></li><li>service-builder-jdk8<ul><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/833511/">service-builder-jdk8/0/0</a></li></ul></li><li>unit-jdk8_stable<ul><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/910594/">unit-jdk8_stable/0/0</a></li></ul></li><li>workspaces-compile-jdk8<ul><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1026222/">workspaces-compile-jdk8/0/0</a></li></ul></li></ul></div><details><summary><strong>31 Successful Jobs:</strong></summary><ul/></details></details><details><summary><strong>ci:test:relevant - 75 out of 80 jobs PASSED</strong></summary><div><h4>5 Failed Jobs:</h4><ul><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest(master)/3610/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>build-iw-jdk8<ul><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/751711/">build-iw-jdk8/0/0</a></li></ul></li><li>central-requirements-jdk8<ul><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/910596/">central-requirements-jdk8/0/0</a></li></ul></li><li>empty-osgi-core-dir-mysql57-jdk8<ul><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/809286/">empty-osgi-core-dir-mysql57-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-db2115-jdk8<ul><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/554545/">functional-smoke-tomcat90-db2115-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-hypersonic20-jdk8<ul><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/751714/">functional-smoke-tomcat90-hypersonic20-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57-jdk11_open<ul><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/80 [...]

2024-02-08 21:35 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:search - 166 out of 181 jobs passed in 2 hours 51 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/7d2acf9f5135c7e3e5d6fcead88cfd2e9e5f19be">7d2acf9f5135c7e3e5d6fcead88cfd2e9e5f19be</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/e5cd9b9d7fb5332ad7593caa307e433a35796070">e5cd9b9d7fb5332ad7593caa307e433a35796070</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2535608297">EE Development Acceptance (master) - 350 - 2024-02-06[08:41:44]</a></p><details><summary><strong>ci:test:search - 166 out of 181 jobs PASSED</strong></summary><div><h4>15 Failed Jobs:</h4><ul><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest(master)/3609/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>central-requirements-jdk8<ul><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/751766/">central-requirements-jdk8/0/0</a></li></ul></li><li>functional-jboss74-mysql57-jdk8<ul><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/522115/">functional-jboss74-mysql57-jdk8/0/0</a></li></ul></li><li>functional-tomcat90-mysql57-jdk8<ul><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/798317/"><strike>functional-tomcat90-mysql57-jdk8/0/0</strike></a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1026268/">functional-tomcat90-mysql57-jdk8/0/1</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/894694/">functional-tomcat90-mysql57-jdk8/0/2</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/554589/">functional-tomcat90-mysql57-jdk8/0/3</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/844953/">functional-tomcat90-mysql57-jdk8/0/4</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1026269/">functional-tomcat90-mysql57-jdk8/0/5</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/798318/">functional-tomcat90-mysql57-jdk8/0/6</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/798319/">functional-tomcat90-mysql57-jdk8/0/7</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/809329/">functional-tomcat90-mysql57-jdk8/0/8</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/836501/">functional-tomcat90-mysql57-jdk8/0/9</a></li><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/350244/">functional-tomcat90-mysql57-jdk8/1/0</a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/389065/">functional-tomcat90-mysql57-jdk8/1/1</a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/389067/">functional-tomcat90-mysql57-jdk8/1/2</a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/389066/">functional-tomcat90-mysql57-jdk8/1/3</a></li><li><a href="https://test-1-12.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/336219/">functional-tomcat90-mysql57-jdk8/1/4</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/894690/">functional-tomcat90-mysql57-jdk8/1/5</a></li><li><a href="https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/363588/">functional-tomcat90-mysql57-jdk8/1/6</a></li><li><a href="https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/301310/">functional-tomcat90-mysql57-jdk8/1/7</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/894691/">functional-tomcat90-mysql57-jdk8/1/8</a></li><li><a href="https://test-1-15.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/335325/">functional-tomcat90-mysql57-jdk8/1/9</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/809332/">functional-tomcat90-mysql57-jdk8/1/10</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/928129/">functional-tomcat90-mysql57-jdk8/1/11</a></li><li><a href="https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/353984/"><strike>functional-tomcat90-mysql57-jdk8/1/12</strike></a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1027719/">functional-tomcat90-mysql57-jdk8/1/13</a></li><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/307535/">functional-tomcat90-mysql57-jdk8/1/14</a></li><li><a href="https://test-1-12.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/336222/">functional-tomcat90-mysql57-jdk8/1/15</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/833553/">functional-tomcat90-mysql57-jdk8/1/16</a></li><li><a href="https://test-1-18.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/335291/">functional-tomcat90-mysql57-jdk8/1/17</a></li><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/290691/">functional-tomcat90-mysql57-jdk8/1/18</a></li><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/350251/">functional-tomcat90-mysql57-jdk8/1/19</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1027717/">functional-tomcat90-mysql57-jdk8/1/20</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/836503/">functional-tomcat90-mysql57-jdk8/1/21</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/522113/">functional-tomcat90-mysql57-jdk8/1/22</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/798320/">functional-tomcat90-mysql57-jdk8/1/23</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1027718/">functional-tomcat90-mysql57-jdk8/1/24</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/836508/">functional-tomcat90-mysql57-jdk8/2/0</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/751765/">functional-tomcat90-mysql57-jdk8/2/1</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/751764/">functional-tomcat90-mysql57-jdk8/2/2</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/522117/">functional-tomcat90-mysql57-jdk8/2/3</a></li><li><a href="https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/353986/">functional-tomcat90-mysql57-jdk8/2/4</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/836509/">functional-tomcat90-mysql57-jdk8/2/5</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstre [...]

2024-02-08 21:41 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest(master)/3609/">test-portal-acceptance-pullrequest(master)#3609</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/3609/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>search<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-search/liferay-portal/pull/1258">liferay-search#1258</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2536685543">[master] ci:test:search - gustavolimav &gt; liferay-search - PR#1258 - 2024-02-08[10:43:24]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>2536685543<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-32.liferay.com/job/publish-testray-report/30843/">publish-testray-report#30843</a><br/></div></div>

2024-02-09 11:35 UTC, gustavolimav commented
ci:report:2536685543

2024-02-09 11:36 UTC, gustavolimav commented
ci:report:2536680054

2024-02-09 11:37 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running <code>generate testray csv</code> for testrayBuildID: <b>2536680054</b>.</p><p>Job Link: <a href="https://test-1-29.liferay.com/job/generate-testray-csv/60/">generate-testray-csv</a></p>

2024-02-09 11:37 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running <code>generate testray csv</code> for testrayBuildID: <b>2536685543</b>.</p><p>Job Link: <a href="https://test-1-25.liferay.com/job/generate-testray-csv/23/">generate-testray-csv</a></p>

2024-02-09 11:40 UTC, liferay-continuous-integration commented
<h1>Build completed.</h1><p>Testray CSV has been generated successfully for testrayBuildID: <b>2536685543</b>.</p><p>Job Link: <a href="https://test-1-25.liferay.com/job/generate-testray-csv/23/">generate-testray-csv</a></p><p>Testray CSV Link: <a href="https://test-1-25.liferay.com/userContent/jobs/generate-testray-csv/builds/23/testray-results.csv">Testray CSV</a></p>

2024-02-09 11:59 UTC, gustavolimav commented
Tests looks good, I will forward manually

2024-02-09 12:02 UTC, gustavolimav commented
https://github.com/brianchandotcom/liferay-portal/pull/147115

2024-02-09 12:02 UTC, closed without merging