LPD-24353 a11y category facet tabindex
liferay-search/liferay-portal pull request #1323
Opened 2024-04-26 19:34 UTC by oliv-yu

https://liferay.atlassian.net/browse/LPD-24353 - Accessibility error on Category Facet's Vocab Layout template
- LPP said it was against a11y to alternate between checkbox and description when tabulating through the Vocabulary Layout. So, this change will check whether the item has contents first, then give the appropriate tabindex (to tab or not to tab).
- Keypress function added to toggle the tree item

https://liferay.atlassian.net/browse/LPD-24331 - User facet template (compact, label) is not filtering properly due to incorrect data term id
- Not sure if anyone ever noticed, but the user facet templates for compact and label were filtering by the name but not the ID, so just a short update to change it to the filter value 😓

2024-04-26 19:34 UTC, liferay-continuous-integration commented
The following guidelines have been set by the owner of this repository: 
- &nbsp;&nbsp;&nbsp;&nbsp;"Thank you for sending this PR to liferay-search! If you haven't already, take this opportunity to review our [pull request guidelines](https://liferay.atlassian.net/l/cp/MmMP1Sh0). For additional help, reach out via the appropriate channels listed [here](https://liferay.atlassian.net/l/cp/MmMP1Sh0#Communication%2C-point-of-contact)."

2024-04-26 19:34 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2024-04-26 19:41 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-8.liferay.com/job/test-portal-source-format/6731/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-8.liferay.com/userContent/jobs/test-portal-source-format/builds/6731/jenkins-report.html">here</a>.</b></p>

2024-04-26 19:43 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/ef0de3a1e929d7352b75537f6ec1f00a6ec47051">ef0de3a1e929d7352b75537f6ec1f00a6ec47051</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/oliv-yu/liferay-portal/tree/LPD-24353-a11y-category-facet-tabindex">LPD-24353-a11y-category-facet-tabindex</a><br/>Branch GIT ID: <a href="https://github.com/oliv-yu/liferay-portal/commit/62701426339f722e8b585ea530500be06d08d491">62701426339f722e8b585ea530500be06d08d491</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-8.liferay.com/job/test-portal-source-format/6731/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-8.liferay.com/userContent/jobs/test-portal-source-format/builds/6731/jenkins-report.html">here</a>.</h5></details></html>

2024-04-26 19:44 UTC, oliv-yu commented
ci:test:search

2024-04-26 19:45 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>search</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest(master)/4253/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/4253/jenkins-report.html">here</a>.</b></p>

2024-04-26 19:47 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-8.liferay.com/job/test-portal-source-format/6731/">test-portal-source-format#6731</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-8.liferay.com/userContent/jobs/test-portal-source-format/builds/6731/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-search/liferay-portal/pull/1323">liferay-search#1323</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2564001022">[master] ci:test:sf - oliv-yu &gt; liferay-search - PR#1323 - 2024-04-26[12:39:48]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>2564001022<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-8.liferay.com/job/publish-testray-report/4547/">publish-testray-report#4547</a><br/></div></div>

2024-04-26 21:43 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:search - 174 out of 181 jobs passed in 1 hour 58 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/ef0de3a1e929d7352b75537f6ec1f00a6ec47051">ef0de3a1e929d7352b75537f6ec1f00a6ec47051</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/ef0de3a1e929d7352b75537f6ec1f00a6ec47051">ef0de3a1e929d7352b75537f6ec1f00a6ec47051</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2563757851">EE Development Acceptance (master) - 507 - 2024-04-25[09:04:13]</a></p><details><summary><strong>ci:test:search - 174 out of 181 jobs PASSED</strong></summary><div><h4>7 Failed Jobs:</h4><ul><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest(master)/4253/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>central-requirements-jdk8<ul><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/865458/">central-requirements-jdk8/0/0</a></li></ul></li><li>functional-jboss74-mysql57-jdk8<ul><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/972284/">functional-jboss74-mysql57-jdk8/0/0</a></li></ul></li><li>functional-tomcat90-mysql57-jdk8<ul><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/621681/">functional-tomcat90-mysql57-jdk8/0/0</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/904188/">functional-tomcat90-mysql57-jdk8/0/1</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1089165/">functional-tomcat90-mysql57-jdk8/0/2</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/998223/">functional-tomcat90-mysql57-jdk8/0/3</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/942379/">functional-tomcat90-mysql57-jdk8/0/4</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1091188/">functional-tomcat90-mysql57-jdk8/0/5</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/865450/">functional-tomcat90-mysql57-jdk8/0/6</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/621682/">functional-tomcat90-mysql57-jdk8/0/7</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1089166/">functional-tomcat90-mysql57-jdk8/0/8</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/927161/">functional-tomcat90-mysql57-jdk8/0/9</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/927156/">functional-tomcat90-mysql57-jdk8/1/0</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/865442/">functional-tomcat90-mysql57-jdk8/1/1</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/580194/">functional-tomcat90-mysql57-jdk8/1/2</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/621677/">functional-tomcat90-mysql57-jdk8/1/3</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1089160/">functional-tomcat90-mysql57-jdk8/1/4</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/811570/">functional-tomcat90-mysql57-jdk8/1/5</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/988235/">functional-tomcat90-mysql57-jdk8/1/6</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/865447/">functional-tomcat90-mysql57-jdk8/1/7</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/904185/">functional-tomcat90-mysql57-jdk8/1/8</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/811571/">functional-tomcat90-mysql57-jdk8/1/9</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/811579/">functional-tomcat90-mysql57-jdk8/1/10</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/927165/">functional-tomcat90-mysql57-jdk8/1/11</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1089169/">functional-tomcat90-mysql57-jdk8/1/12</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/904192/">functional-tomcat90-mysql57-jdk8/1/13</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/621685/">functional-tomcat90-mysql57-jdk8/1/14</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/580202/">functional-tomcat90-mysql57-jdk8/1/15</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1091192/">functional-tomcat90-mysql57-jdk8/1/16</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/580199/">functional-tomcat90-mysql57-jdk8/1/17</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1091189/">functional-tomcat90-mysql57-jdk8/1/18</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/972280/">functional-tomcat90-mysql57-jdk8/1/19</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/811577/">functional-tomcat90-mysql57-jdk8/1/20</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/942381/">functional-tomcat90-mysql57-jdk8/1/21</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/998225/">functional-tomcat90-mysql57-jdk8/1/22</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/883443/">functional-tomcat90-mysql57-jdk8/1/23</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/811578/">functional-tomcat90-mysql57-jdk8/1/24</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/904195/">functional-tomcat90-mysql57-jdk8/2/0</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1091197/">functional-tomcat90-mysql57-jdk8/2/1</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/580206/">functional-tomcat90-mysql57-jdk8/2/2</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/864557/">functional-tomcat90-mysql57-jdk8/2/3</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/580205/">functional-tomcat90-mysql57-jdk8/2/4</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1089174/">functional-tomcat90-mysql57-jdk8/2/5</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/811584/">func [...]

2024-04-26 21:46 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest(master)/4253/">test-portal-acceptance-pullrequest(master)#4253</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/4253/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>search<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-search/liferay-portal/pull/1323">liferay-search#1323</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2564016881">[master] ci:test:search - oliv-yu &gt; liferay-search - PR#1323 - 2024-04-26[12:44:11]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>2564016881<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-32.liferay.com/job/publish-testray-report/32219/">publish-testray-report#32219</a><br/></div></div>

2024-04-30 23:32 UTC, thektan requested changes
Just 1 small addition and it can be forwarded afterwards!

2024-04-30 23:32 UTC, thektan commented on modules/apps/portal-search/portal-search-web/src/main/resources/com/liferay/portal/search/web/internal/category/facet/portlet/display/template/dependencies/portlet_display_template_vocabulary.ftl
> +		if (event.code === 'Enter') {
`Space` should also toggle the tree item.

2024-04-30 23:55 UTC, oliv-yu commented
ci:forward

2024-04-30 23:55 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

The pull request will automatically be forwarded to the user `brianchandotcom` If the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2024-04-30 23:56 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest(master)/11747/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/11747/jenkins-report.html">here</a>.</b></p>

2024-04-30 23:57 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-33.liferay.com/job/test-portal-source-format/2988/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-33.liferay.com/userContent/jobs/test-portal-source-format/builds/2988/jenkins-report.html">here</a>.</b></p>

2024-04-30 23:59 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/b9f49e7e1f1895470322f051fd388848ebd12815">b9f49e7e1f1895470322f051fd388848ebd12815</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/oliv-yu/liferay-portal/tree/LPD-24353-a11y-category-facet-tabindex">LPD-24353-a11y-category-facet-tabindex</a><br/>Branch GIT ID: <a href="https://github.com/oliv-yu/liferay-portal/commit/0ceab400693a8da43cff2d6d0987f1b2903763ad">0ceab400693a8da43cff2d6d0987f1b2903763ad</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-33.liferay.com/job/test-portal-source-format/2988/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-33.liferay.com/userContent/jobs/test-portal-source-format/builds/2988/jenkins-report.html">here</a>.</h5></details></html>

2024-05-01 01:38 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:stable - 30 out of 30 jobs passed</h3><h3>:heavy_check_mark: ci:test:relevant - 45 out of 45 jobs passed in 1 hour 42 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/b9f49e7e1f1895470322f051fd388848ebd12815">b9f49e7e1f1895470322f051fd388848ebd12815</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/ad9a41c8204eb253c2313bcf2e1fd25c610f80da">ad9a41c8204eb253c2313bcf2e1fd25c610f80da</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2564760023">EE Development Acceptance (master) - 516 - 2024-04-30[12:38:45]</a></p><details><summary><strong>ci:test:stable - 30 out of 30 jobs PASSED</strong></summary><details><summary><strong>30 Successful Jobs:</strong></summary><ul><li>build-iw-jdk8<ul><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/870478/">build-iw-jdk8/0/0</a></li></ul></li><li>central-requirements-jdk8<ul><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/333149/">central-requirements-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57-jdk8_stable<ul><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/870479/">functional-smoke-tomcat90-mysql57-jdk8_stable/0/0</a></li></ul></li><li>functional-upgrade-tomcat90-mysql57-jdk8_stable<ul><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/870497/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/0</a></li><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/333150/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/1</a></li><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/381401/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/2</a></li><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/381402/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/3</a></li><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/315546/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/4</a></li><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/315547/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/5</a></li></ul></li><li>js-unit-jdk8<ul><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/381400/">js-unit-jdk8/0/0</a></li></ul></li><li>modules-compile-jdk8<ul><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/870486/">modules-compile-jdk8/0/0</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/870488/">modules-compile-jdk8/0/1</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/870490/">modules-compile-jdk8/0/2</a></li><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/333143/">modules-compile-jdk8/0/3</a></li><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/333146/">modules-compile-jdk8/0/4</a></li><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/333147/">modules-compile-jdk8/0/5</a></li><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/333148/">modules-compile-jdk8/0/6</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/870496/">modules-compile-jdk8/0/7</a></li><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/333145/">modules-compile-jdk8/0/8</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/870493/">modules-compile-jdk8/0/9</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/870487/">modules-compile-jdk8/0/10</a></li><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/333144/">modules-compile-jdk8/0/11</a></li></ul></li><li>modules-integration-mysql57-jdk8_stable<ul><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/870498/">modules-integration-mysql57-jdk8_stable/0/0</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/884562/">modules-integration-mysql57-jdk8_stable/0/1</a></li></ul></li><li>modules-unit-jdk8_stable<ul><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/870494/">modules-unit-jdk8_stable/0/0</a></li></ul></li><li>playwright-compile-jdk8<ul><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/870476/">playwright-compile-jdk8/0/0</a></li></ul></li><li>playwright-js-tomcat90-mysql57-jdk8_stable<ul><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/870492/">playwright-js-tomcat90-mysql57-jdk8_stable/0/0</a></li></ul></li><li>service-builder-jdk8<ul><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/870495/">service-builder-jdk8/0/0</a></li></ul></li><li>unit-jdk8_stable<ul><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/870475/">unit-jdk8_stable/0/0</a></li></ul></li><li>workspaces-compile-jdk8<ul><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/870474/">workspaces-compile-jdk8/0/0</a></li></ul></li></ul></details></details><details><summary><strong>ci:test:relevant - 45 out of 45 jobs PASSED</strong></summary><details><summary><strong>45 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest(master)/11747/">test-portal-acceptance-pullrequest(master)</a></li><li>build-iw-jdk8<ul><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/870478/">build-iw-jdk8/0/0</a></li></ul></li><li>central-requirements-jdk8<ul><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/333149/">central-requirements-jdk8/0/0</a></li></ul></li><li>empty-osgi-core-dir-mysql57-jdk8<ul><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/870473/">empty-osgi-core-dir-mysql57-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57-jdk8_stable<ul><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/870479/">functional-smoke-tomcat90-mysql57-jdk8_stable/0/0</a></li></ul></li><li>functional-upgrade-tomcat90-mysql57-jdk8_stable<ul><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/870497/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/0</a></li><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/333150/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/1</a></li><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/381401/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/2</a></li><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/381402/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/3</a></li><li><a hr [...]

2024-05-01 01:38 UTC, liferay-continuous-integration commented
All required test suite(s) passed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest(master)/11747//consoleFull)

2024-05-01 01:39 UTC, closed without merging

2024-05-01 01:39 UTC, liferay-continuous-integration commented
Pull request has been successfully forwarded to  https://github.com/brianchandotcom/liferay-portal/pull/149842
[Console](https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest(master)/11747//consoleFull)

2024-05-01 01:41 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest(master)/11747/">test-portal-acceptance-pullrequest(master)#11747</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/11747/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-search/liferay-portal/pull/1323">liferay-search#1323</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2564780670">[master] ci:test:relevant - oliv-yu &gt; liferay-search - PR#1323 - 2024-04-30[16:55:49]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>2564780670<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-27.liferay.com/job/publish-testray-report/25640/">publish-testray-report#25640</a><br/></div></div>