LPD-30647 test
liferay-search/liferay-portal pull request #1418
Opened 2024-07-25 23:59 UTC by joshuacords

Follow up tests for: https://github.com/brianchandotcom/liferay-portal/pull/152641#issuecomment-2249572859

**Author:** @joshuacords

2024-07-25 23:59 UTC, liferay-continuous-integration commented
The following guidelines have been set by the owner of this repository: 
- &nbsp;&nbsp;&nbsp;&nbsp;"Thank you for sending this PR to liferay-search! If you haven't already, take this opportunity to review our [pull request guidelines](https://liferay.atlassian.net/l/cp/MmMP1Sh0). For additional help, reach out via the appropriate channels listed [here](https://liferay.atlassian.net/l/cp/MmMP1Sh0#Communication%2C-point-of-contact)."

2024-07-25 23:59 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2024-07-25 23:59 UTC, joshuacords commented
ci:test:sf

2024-07-25 23:59 UTC, joshuacords commented
ci:test:search

2024-07-25 23:59 UTC, joshuacords commented
ci:test:search-opensearch2

2024-07-26 00:00 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>search</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest(master)/6539/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-36.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/6539/jenkins-report.html">here</a>.</b></p>

2024-07-26 00:00 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>search-opensearch2</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest(master)/4686/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/4686/jenkins-report.html">here</a>.</b></p>

2024-07-26 00:01 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-27.liferay.com/job/test-portal-source-format/7017/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/7017/jenkins-report.html">here</a>.</b></p>

2024-07-26 00:03 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/332034550637e81c98183781dd12a0659fc176a6">332034550637e81c98183781dd12a0659fc176a6</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/joshuacords/liferay-portal/tree/JCords-LPD-30647-test">JCords-LPD-30647-test</a><br/>Branch GIT ID: <a href="https://github.com/joshuacords/liferay-portal/commit/437a612fe7b3e775f69adfe95813645eb971864c">437a612fe7b3e775f69adfe95813645eb971864c</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-27.liferay.com/job/test-portal-source-format/7017/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/7017/jenkins-report.html">here</a>.</h5></details></html>

2024-07-26 00:05 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-27.liferay.com/job/test-portal-source-format/7017/">test-portal-source-format#7017</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/7017/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-search/liferay-portal/pull/1418">liferay-search#1418</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756/build/45783478">[master] ci:test:sf - joshuacords &gt; liferay-search - PR#1418 - 2024-07-25[16:59:43]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>45783478<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-27.liferay.com/job/publish-testray-report/26833/">publish-testray-report#26833</a><br/></div></div>

2024-07-26 02:46 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:search - 177 out of 185 jobs passed in 2 hours 42 minutes</h3><details><summary>Click here for more details.</summary><br/><p>This pull is eligible for <a href="https://grow.liferay.com/share/CI+liferay-continuous-integration+GitHub+Commands#General-Commands">reevaluation</a>. When this <a href="https://test-1-40.liferay.com/job/test-portal-acceptance-upstream-dxp(master)/702">upstream build</a> has completed, using the following CI command will compare this pull request result against a more recent upstream result:<pre>ci:reevaluate:1367401_6539</pre></p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/332034550637e81c98183781dd12a0659fc176a6">332034550637e81c98183781dd12a0659fc176a6</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/709117be333ef82d320d1c19a9060d9f9e02d17a">709117be333ef82d320d1c19a9060d9f9e02d17a</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/#/project/34754/routines/174485/build/45758234">EE Development Acceptance (master) - 701 - 2024-07-25[12:40:55]</a></p><details><summary><strong>ci:test:search - 177 out of 185 jobs PASSED</strong></summary><div><h4>8 Failed Jobs:</h4><ul><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest(master)/6539/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>central-requirements-jdk8<ul><li><a href="https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/354820/">central-requirements-jdk8/0/0</a></li></ul></li><li>functional-jboss74-mysql57-jdk8<ul><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/945349/">functional-jboss74-mysql57-jdk8/0/0</a></li></ul></li><li>functional-tomcat90-mysql57-jdk8<ul><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1052761/">functional-tomcat90-mysql57-jdk8/0/0</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/945344/">functional-tomcat90-mysql57-jdk8/0/1</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1165321/">functional-tomcat90-mysql57-jdk8/0/2</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1165322/">functional-tomcat90-mysql57-jdk8/0/3</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/695927/"><strike>functional-tomcat90-mysql57-jdk8/0/4</strike></a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/946972/">functional-tomcat90-mysql57-jdk8/0/5</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1010716/">functional-tomcat90-mysql57-jdk8/0/6</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/946973/">functional-tomcat90-mysql57-jdk8/0/7</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1040457/">functional-tomcat90-mysql57-jdk8/0/8</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/999590/"><strike>functional-tomcat90-mysql57-jdk8/0/9</strike></a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/642624/">functional-tomcat90-mysql57-jdk8/1/0</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/969811/">functional-tomcat90-mysql57-jdk8/1/1</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/945341/">functional-tomcat90-mysql57-jdk8/1/2</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1062178/">functional-tomcat90-mysql57-jdk8/1/3</a></li><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/425605/">functional-tomcat90-mysql57-jdk8/1/4</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/946970/">functional-tomcat90-mysql57-jdk8/1/5</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/945342/">functional-tomcat90-mysql57-jdk8/1/6</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1062179/">functional-tomcat90-mysql57-jdk8/1/7</a></li><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/454672/">functional-tomcat90-mysql57-jdk8/1/8</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/969812/">functional-tomcat90-mysql57-jdk8/1/9</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1052765/">functional-tomcat90-mysql57-jdk8/1/10</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1010720/">functional-tomcat90-mysql57-jdk8/1/11</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/880207/">functional-tomcat90-mysql57-jdk8/1/12</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/642630/">functional-tomcat90-mysql57-jdk8/1/13</a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/452017/">functional-tomcat90-mysql57-jdk8/1/14</a></li><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/406367/">functional-tomcat90-mysql57-jdk8/1/15</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/942960/">functional-tomcat90-mysql57-jdk8/1/16</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1165323/">functional-tomcat90-mysql57-jdk8/1/17</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1062183/">functional-tomcat90-mysql57-jdk8/1/18</a></li><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/425607/">functional-tomcat90-mysql57-jdk8/1/19</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1052763/">functional-tomcat90-mysql57-jdk8/1/20</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/880206/">functional-tomcat90-mysql57-jdk8/1/21</a></li><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/346394/">functional-tomcat90-mysql57-jdk8/1/22</a></li><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/454677/">functional-tomcat90-mysql57-jdk8/1/23</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1062184/">functional-tomcat90-mysql57-jdk8/1/24</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/969821/">functional-tomcat90-mysql57-jdk8/2/0</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/999594/">functional-tomcat90-mysql57-jdk8/2/1</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/942964/">functional-tomcat90-mysql57-jdk8/2/2</a></li><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/346 [...]

2024-07-26 02:50 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest(master)/6539/">test-portal-acceptance-pullrequest(master)#6539</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-36.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/6539/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>search<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-search/liferay-portal/pull/1418">liferay-search#1418</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756/build/45913884">[master] ci:test:search - joshuacords &gt; liferay-search - PR#1418 - 2024-07-25[16:59:49]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>45913884<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-36.liferay.com/job/publish-testray-report/14548/">publish-testray-report#14548</a><br/></div></div>

2024-07-26 03:15 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:search-opensearch2 - 149 out of 159 jobs passed in 3 hours 14 minutes</h3><details><summary>Click here for more details.</summary><br/><p>This pull is eligible for <a href="https://grow.liferay.com/share/CI+liferay-continuous-integration+GitHub+Commands#General-Commands">reevaluation</a>. When this <a href="https://test-1-40.liferay.com/job/test-portal-acceptance-upstream-dxp(master)/702">upstream build</a> has completed, using the following CI command will compare this pull request result against a more recent upstream result:<pre>ci:reevaluate:1327401_4686</pre></p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/332034550637e81c98183781dd12a0659fc176a6">332034550637e81c98183781dd12a0659fc176a6</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/709117be333ef82d320d1c19a9060d9f9e02d17a">709117be333ef82d320d1c19a9060d9f9e02d17a</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/#/project/34754/routines/174485/build/45758234">EE Development Acceptance (master) - 701 - 2024-07-25[12:40:55]</a></p><details><summary><strong>ci:test:search-opensearch2 - 149 out of 159 jobs PASSED</strong></summary><div><h4>10 Failed Jobs:</h4><ul><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest(master)/4686/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>central-requirements-jdk8<ul><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/969832/">central-requirements-jdk8/0/0</a></li></ul></li><li>functional-tomcat90-mysql57-jdk8<ul><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/969825/">functional-tomcat90-mysql57-jdk8/0/0</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/945356/">functional-tomcat90-mysql57-jdk8/1/0</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/999596/">functional-tomcat90-mysql57-jdk8/1/1</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/945358/">functional-tomcat90-mysql57-jdk8/1/2</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/999598/">functional-tomcat90-mysql57-jdk8/1/3</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/945357/">functional-tomcat90-mysql57-jdk8/1/4</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/999597/">functional-tomcat90-mysql57-jdk8/1/5</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/880211/">functional-tomcat90-mysql57-jdk8/1/6</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/999600/">functional-tomcat90-mysql57-jdk8/1/7</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/880210/">functional-tomcat90-mysql57-jdk8/1/8</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/999599/">functional-tomcat90-mysql57-jdk8/1/9</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/969828/">functional-tomcat90-mysql57-jdk8/1/10</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/945367/">functional-tomcat90-mysql57-jdk8/1/11</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1160594/">functional-tomcat90-mysql57-jdk8/1/12</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/942975/">functional-tomcat90-mysql57-jdk8/1/13</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1165333/">functional-tomcat90-mysql57-jdk8/1/14</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/946983/">functional-tomcat90-mysql57-jdk8/1/15</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1062189/">functional-tomcat90-mysql57-jdk8/1/16</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/642636/">functional-tomcat90-mysql57-jdk8/1/17</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/999605/">functional-tomcat90-mysql57-jdk8/1/18</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1040467/">functional-tomcat90-mysql57-jdk8/1/19</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1052770/">functional-tomcat90-mysql57-jdk8/1/20</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/642637/">functional-tomcat90-mysql57-jdk8/1/21</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/969827/">functional-tomcat90-mysql57-jdk8/1/22</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/945365/">functional-tomcat90-mysql57-jdk8/1/23</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/880216/">functional-tomcat90-mysql57-jdk8/1/24</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1160597/">functional-tomcat90-mysql57-jdk8/2/0</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1052776/">functional-tomcat90-mysql57-jdk8/2/1</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/999613/">functional-tomcat90-mysql57-jdk8/2/2</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/920449/">functional-tomcat90-mysql57-jdk8/2/3</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/695937/">functional-tomcat90-mysql57-jdk8/2/4</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/945371/">functional-tomcat90-mysql57-jdk8/2/5</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/942981/">functional-tomcat90-mysql57-jdk8/2/6</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/642642/">functional-tomcat90-mysql57-jdk8/2/7</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/999614/">functional-tomcat90-mysql57-jdk8/2/8</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/945353/">functional-tomcat90-mysql57-jdk8/2/9</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1040465/">functional-tomcat90-mysql57-jdk8/2/10</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/969824/"><strike>functional-tomcat90-mysql57-jdk8/2/11</strike></a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/880213/"><strike>functional-tomcat90-mysql57-jdk8/2/12</strike></a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1165329/">functiona [...]

2024-07-26 03:19 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest(master)/4686/">test-portal-acceptance-pullrequest(master)#4686</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/4686/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>search-opensearch2<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-search/liferay-portal/pull/1418">liferay-search#1418</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756/build/45972690">[master] ci:test:search-opensearch2 - joshuacords &gt; liferay-search - PR#1418 - 2024-07-25[17:00:00]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>45972690<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-32.liferay.com/job/publish-testray-report/33165/">publish-testray-report#33165</a><br/></div></div>

2024-07-26 15:50 UTC, joshuacords commented
ci:report:45972690

On Thu, Jul 25, 2024, 8:19 PM Liferay Continuous Integration <
***@***.***> wrote:

> *Jenkins Build:*test-portal-acceptance-pullrequest(master)#4686
> <https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest(master)/4686/>
> *Jenkins Report:*jenkins-report.html
> <https://test-1-32.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/4686/jenkins-report.html>
> *Jenkins Suite:*search-opensearch2
> *Pull Request:*liferay-search#1418
> <https://github.com/liferay-search/liferay-portal/pull/1418>
> *Testray Routine:*EE Pull Request
> <https://testray.liferay.com/#/project/34754/routines/34756>
> *Testray Build:*[master] ci:test:search-opensearch2 - joshuacords >
> liferay-search - PR#1418 - 2024-07-25[17:00:00]
> <https://testray.liferay.com/#/project/34754/routines/34756/build/45972690>
> *Testray Build ID:*45972690
> *Testray Importer:*publish-testray-report#33165
> <https://test-1-32.liferay.com/job/publish-testray-report/33165/>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/liferay-search/liferay-portal/pull/1418#issuecomment-2251886588>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AEY7ODNOG4YZAXOUZVIKC6LZOG55PAVCNFSM6AAAAABLPQATVWVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDENJRHA4DMNJYHA>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-07-26 15:50 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running <code>generate testray csv</code> for testrayBuildID: <b>45972690</b>.</p><p>Job Link: <a href="https://test-1-40.liferay.com/job/generate-testray-csv/412/">generate-testray-csv</a></p>

2024-07-26 15:54 UTC, liferay-continuous-integration commented
<h1>Build completed.</h1><p>Testray CSV has been generated successfully for testrayBuildID: <b>45972690</b>.</p><p>Job Link: <a href="https://test-1-40.liferay.com/job/generate-testray-csv/412/">generate-testray-csv</a></p><p>Testray CSV Link: <a href="https://test-1-40.liferay.com/userContent/jobs/generate-testray-csv/builds/412/testray-results-45972690.csv">testray-results-45972690.csv</a></p>

2024-07-26 20:18 UTC, joshuacords commented
ci:test:relevant

2024-07-26 20:19 UTC, joshuacords commented
ci:report:45913884

2024-07-26 20:19 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running <code>generate testray csv</code> for testrayBuildID: <b>45913884</b>.</p><p>Job Link: <a href="https://test-1-39.liferay.com/job/generate-testray-csv/341/">generate-testray-csv</a></p>

2024-07-26 20:21 UTC, liferay-continuous-integration commented
<h1>Build completed.</h1><p>Testray CSV has been generated successfully for testrayBuildID: <b>45913884</b>.</p><p>Job Link: <a href="https://test-1-39.liferay.com/job/generate-testray-csv/341/">generate-testray-csv</a></p><p>Testray CSV Link: <a href="https://test-1-39.liferay.com/userContent/jobs/generate-testray-csv/builds/341/testray-results-45913884.csv">testray-results-45913884.csv</a></p>

2024-07-26 21:29 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest(master)/10855/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/10855/jenkins-report.html">here</a>.</b></p>

2024-07-26 23:25 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:stable - 4 out of 4 jobs passed</h3><h3>:heavy_check_mark: ci:test:relevant - 12 out of 16 jobs passed in 1 hour 57 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/c16e65131bb9e8393356423a33f6b57c5d833d86">c16e65131bb9e8393356423a33f6b57c5d833d86</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/332034550637e81c98183781dd12a0659fc176a6">332034550637e81c98183781dd12a0659fc176a6</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/#/project/34754/routines/174485/build/45987663">EE Development Acceptance (master) - 702 - 2024-07-25[16:42:44]</a></p><details><summary><strong>ci:test:stable - 4 out of 4 jobs PASSED</strong></summary><details><summary><strong>4 Successful Jobs:</strong></summary><ul/></details></details><details><summary><strong>ci:test:relevant - 11 out of 16 jobs PASSED</strong></summary><div><h4>5 Failed Jobs:</h4><ul><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest(master)/10855/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>modules-integration-mysql57-jdk8<ul><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/945790/">modules-integration-mysql57-jdk8/0/0</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/643198/">modules-integration-mysql57-jdk8/0/1</a></li></ul></li><li>modules-integration-mysql57-jdk8_stable<ul><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1000101/">modules-integration-mysql57-jdk8_stable/0/0</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/643280/">modules-integration-mysql57-jdk8_stable/0/1</a></li></ul></li><li>modules-unit-jdk8<ul><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1000103/">modules-unit-jdk8/0/0</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1062592/">modules-unit-jdk8/0/1</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/696520/">modules-unit-jdk8/0/2</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/918448/">modules-unit-jdk8/0/3</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1053242/"><strike>modules-unit-jdk8/0/4</strike></a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/918449/"><strike>modules-unit-jdk8/0/5</strike></a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/947350/"><strike>modules-unit-jdk8/0/6</strike></a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/945789/"><strike>modules-unit-jdk8/0/7</strike></a></li></ul></li><li>modules-unit-jdk8_stable<ul><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1000100/">modules-unit-jdk8_stable/0/0</a></li></ul></li><li>unit-jdk8<ul><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/943501/">unit-jdk8/0/0</a></li></ul></li><li>unit-jdk8_stable<ul><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1011436/">unit-jdk8_stable/0/0</a></li></ul></li></ul></div><details><summary><strong>11 Successful Jobs:</strong></summary><ul/></details></details><h5>For more details click <a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/10855/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1053242//consoleText">modules-unit-jdk8/0/4</a><ol><li><div>com.liferay.portal.search.opensearch2.internal.cluster.ReplicasClusterListenerTest.testAHappyDay - UNTESTED</div></li><li><div>com.liferay.portal.search.opensearch2.internal.cluster.ReplicasClusterListenerTest.testLiferayClusterReportsEmpty - UNTESTED</div></li><li><div>com.liferay.portal.search.opensearch2.internal.cluster.ReplicasClusterListenerTest.testMasterTokenAcquired - UNTESTED</div></li><li>...</li></ol></div></li><li><div><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/918449//consoleText">modules-unit-jdk8/0/5</a><ol><li><div>com.liferay.portal.search.opensearch2.internal.logging.OpenSearchExceptionHandlerTest.testDeleteIndexNotFoundLogExceptionsOnlyFalse - UNTESTED</div></li><li><div>com.liferay.portal.search.opensearch2.internal.logging.OpenSearchExceptionHandlerTest.testDeleteIndexNotFoundLogExceptionsOnlyTrue - UNTESTED</div></li><li><div>com.liferay.portal.search.opensearch2.internal.logging.OpenSearchExceptionHandlerTest.testDeleteLogExceptionsOnlyFalse - UNTESTED</div></li><li>...</li></ol></div></li><li><div><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/947350//consoleText">modules-unit-jdk8/0/6</a><ol><li><div>com.liferay.portal.search.opensearch2.internal.mappings.AssetTagNamesFieldQueryBuilderTest.testBasicWordMatches - UNTESTED</div></li><li><div>com.liferay.portal.search.opensearch2.internal.mappings.AssetTagNamesFieldQueryBuilderTest.testMultiwordPhrasePrefixesOpenSearch - UNTESTED</div></li><li><div>com.liferay.portal.search.opensearch2.internal.mappings.AssetTagNamesFieldQueryBuilderTest.testMultiwordPrefixes - UNTESTED</div></li><li>...</li></ol></div></li></ol><hr/><details><summary><strong>Failures in common with <a href="https://test-1-40.liferay.com/job/test-portal-acceptance-upstream-dxp(master)">acceptance upstream results</a> at 332034550637e81c98183781dd12a0659fc176a6:</strong></summary><ol><li><div><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1053242//consoleText">modules-unit-jdk8/0/4</a><ol><li><details><summary><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1053242/testReport/com.liferay.portal.search.opensearch2.internal.aggregation/BucketSelectorPipelineAggregationTest">com.liferay.portal.search.opensearch2.internal.aggregation.BucketSelectorPipelineAggregationTest</a> - <a>Failed 22 of last 22</a></summary><div><ol><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1053242//testReport/com.liferay.portal.search.opensearch2.internal.aggregation/BucketSelectorPipelineAggregationTest/testRun">testRun</a></li></ol></div></details></li><li><details><summary><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1053242/testReport/com.liferay.portal.search.opensearch2.internal.aggregation/SumAggregationTest">com.liferay.portal.search.opensearch2.internal.aggregation.SumAggregationTest</a> - <a>Failed 22 of last 22</a></summary><div><ol><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1053242//testReport/com.liferay.portal.search.opensearch2.internal.aggregation/SumAggregationTest/testRun">testRun</a></li></ol></div></details></li><li><details><summary><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1053242/testReport/com.liferay.portal.search.opensearch2.internal.aggregation/PercentileRanksAggregationTest">com.liferay.portal.search.opensearch2.internal.aggregation.PercentileRanksAggregationTest</a> - <a [...]

2024-07-26 23:36 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest(master)/10855/">test-portal-acceptance-pullrequest(master)#10855</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/10855/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-search/liferay-portal/pull/1418">liferay-search#1418</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756/build/46441758">[master] ci:test:relevant - joshuacords &gt; liferay-search - PR#1418 - 2024-07-26[14:28:56]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>46441758<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-39.liferay.com/job/publish-testray-report/23271/">publish-testray-report#23271</a><br/></div></div>

2024-07-29 12:37 UTC, gustavolimav requested changes

2024-07-29 12:37 UTC, gustavolimav commented on modules/apps/portal-search-opensearch2/portal-search-opensearch2-impl/src/test/java/com/liferay/portal/search/opensearch2/internal/OpenSearchIndexWriterTest.java
> +	public void testPartiallyUpdateUpsertsMissingDocument()
Maybe rename `testPartiallyUpdateDocumentUpsertsMissingDocument` as we are testing the `partiallyUpdateDocument` method right?

2024-07-29 12:38 UTC, gustavolimav commented
Other than that code LGTM!

2024-07-29 23:25 UTC, joshuacords commented
ci:forward

2024-07-29 23:25 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

The pull request will automatically be forwarded to the user `brianchandotcom` If the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2024-07-29 23:28 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-3.liferay.com/job/test-portal-source-format/7959/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-3.liferay.com/userContent/jobs/test-portal-source-format/builds/7959/jenkins-report.html">here</a>.</b></p>

2024-07-29 23:31 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/c16e65131bb9e8393356423a33f6b57c5d833d86">c16e65131bb9e8393356423a33f6b57c5d833d86</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/joshuacords/liferay-portal/tree/JCords-LPD-30647-test">JCords-LPD-30647-test</a><br/>Branch GIT ID: <a href="https://github.com/joshuacords/liferay-portal/commit/0ca96301fb3d30f35788e664b979f610568581f5">0ca96301fb3d30f35788e664b979f610568581f5</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-3.liferay.com/job/test-portal-source-format/7959/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-3.liferay.com/userContent/jobs/test-portal-source-format/builds/7959/jenkins-report.html">here</a>.</h5></details></html>

2024-07-29 23:33 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-3.liferay.com/job/test-portal-source-format/7959/">test-portal-source-format#7959</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-3.liferay.com/userContent/jobs/test-portal-source-format/builds/7959/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-search/liferay-portal/pull/1418">liferay-search#1418</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756/build/47554442">[master] ci:test:sf - joshuacords &gt; liferay-search - PR#1418 - 2024-07-29[16:27:03]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>47554442<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-3.liferay.com/job/publish-testray-report/4329/">publish-testray-report#4329</a><br/></div></div>

2024-07-29 23:46 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest(master)/12298/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/12298/jenkins-report.html">here</a>.</b></p>

2024-07-30 00:54 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:stable - 4 out of 4 jobs passed</h3><h3>:heavy_check_mark: ci:test:relevant - 12 out of 16 jobs passed in 1 hour 8 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/c16e65131bb9e8393356423a33f6b57c5d833d86">c16e65131bb9e8393356423a33f6b57c5d833d86</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/c16e65131bb9e8393356423a33f6b57c5d833d86">c16e65131bb9e8393356423a33f6b57c5d833d86</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/#/project/34754/routines/174485/build/46441504">EE Development Acceptance (master) - 703 - 2024-07-26[08:41:06]</a></p><details><summary><strong>ci:test:stable - 4 out of 4 jobs PASSED</strong></summary><details><summary><strong>4 Successful Jobs:</strong></summary><ul/></details></details><details><summary><strong>ci:test:relevant - 11 out of 16 jobs PASSED</strong></summary><div><h4>5 Failed Jobs:</h4><ul><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest(master)/12298/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>modules-integration-mysql57-jdk8<ul><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/644501/">modules-integration-mysql57-jdk8/0/0</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1054400/">modules-integration-mysql57-jdk8/0/1</a></li></ul></li><li>modules-integration-mysql57-jdk8_stable<ul><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1054399/">modules-integration-mysql57-jdk8_stable/0/0</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1167195/">modules-integration-mysql57-jdk8_stable/0/1</a></li></ul></li><li>modules-unit-jdk8<ul><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1042318/">modules-unit-jdk8/0/0</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/971456/">modules-unit-jdk8/0/1</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/921780/">modules-unit-jdk8/0/2</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/921779/">modules-unit-jdk8/0/3</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/971455/"><strike>modules-unit-jdk8/0/4</strike></a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1162134/"><strike>modules-unit-jdk8/0/5</strike></a></li><li><a href="https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/355032/"><strike>modules-unit-jdk8/0/6</strike></a></li><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/454943/"><strike>modules-unit-jdk8/0/7</strike></a></li></ul></li><li>modules-unit-jdk8_stable<ul><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1042319/">modules-unit-jdk8_stable/0/0</a></li></ul></li><li>unit-jdk8<ul><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/919177/">unit-jdk8/0/0</a></li></ul></li><li>unit-jdk8_stable<ul><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/948497/">unit-jdk8_stable/0/0</a></li></ul></li></ul></div><details><summary><strong>11 Successful Jobs:</strong></summary><ul/></details></details><h5>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/12298/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/971455//consoleText">modules-unit-jdk8/0/4</a><ol><li><div>com.liferay.portal.search.opensearch2.internal.cluster.ReplicasClusterListenerTest.testAHappyDay - UNTESTED</div></li><li><div>com.liferay.portal.search.opensearch2.internal.cluster.ReplicasClusterListenerTest.testLiferayClusterReportsEmpty - UNTESTED</div></li><li><div>com.liferay.portal.search.opensearch2.internal.cluster.ReplicasClusterListenerTest.testMasterTokenAcquired - UNTESTED</div></li><li>...</li></ol></div></li><li><div><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1162134//consoleText">modules-unit-jdk8/0/5</a><ol><li><div>com.liferay.portal.search.opensearch2.internal.logging.OpenSearchExceptionHandlerTest.testDeleteIndexNotFoundLogExceptionsOnlyFalse - UNTESTED</div></li><li><div>com.liferay.portal.search.opensearch2.internal.logging.OpenSearchExceptionHandlerTest.testDeleteIndexNotFoundLogExceptionsOnlyTrue - UNTESTED</div></li><li><div>com.liferay.portal.search.opensearch2.internal.logging.OpenSearchExceptionHandlerTest.testDeleteLogExceptionsOnlyFalse - UNTESTED</div></li><li>...</li></ol></div></li><li><div><a href="https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/355032//consoleText">modules-unit-jdk8/0/6</a><ol><li><div>com.liferay.portal.search.opensearch2.internal.mappings.AssetTagNamesFieldQueryBuilderTest.testBasicWordMatches - UNTESTED</div></li><li><div>com.liferay.portal.search.opensearch2.internal.mappings.AssetTagNamesFieldQueryBuilderTest.testMultiwordPhrasePrefixesOpenSearch - UNTESTED</div></li><li><div>com.liferay.portal.search.opensearch2.internal.mappings.AssetTagNamesFieldQueryBuilderTest.testMultiwordPrefixes - UNTESTED</div></li><li>...</li></ol></div></li></ol><hr/><details><summary><strong>Failures in common with <a href="https://test-1-40.liferay.com/job/test-portal-acceptance-upstream-dxp(master)">acceptance upstream results</a> at c16e65131bb9e8393356423a33f6b57c5d833d86:</strong></summary><ol><li><div><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/971455//consoleText">modules-unit-jdk8/0/4</a><ol><li><details><summary><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/971455/testReport/com.liferay.portal.search.opensearch2.internal.aggregation/BucketSelectorPipelineAggregationTest">com.liferay.portal.search.opensearch2.internal.aggregation.BucketSelectorPipelineAggregationTest</a> - <a href="https://testray.liferay.com/home/-/testray/case_results/47009691/history">Failed 23 of last 23</a></summary><div><ol><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/971455//testReport/com.liferay.portal.search.opensearch2.internal.aggregation/BucketSelectorPipelineAggregationTest/testRun">testRun</a></li></ol></div></details></li><li><details><summary><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/971455/testReport/com.liferay.portal.search.opensearch2.internal.aggregation/SumAggregationTest">com.liferay.portal.search.opensearch2.internal.aggregation.SumAggregationTest</a> - <a href="https://testray.liferay.com/home/-/testray/case_results/47009911/history">Failed 23 of last 23</a></summary><div><ol><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/971455//testReport/com.liferay.portal.search.opensearch2.internal.aggregation/SumAggregationTest/testRun">testRun</a></li></ol></div></details></li><li><details><summary><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/971455/testReport/com.liferay.portal.search.opensearch2.i [...]

2024-07-30 00:54 UTC, liferay-continuous-integration commented
All required test suite(s) passed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest(master)/12298//consoleFull)

2024-07-30 00:55 UTC, closed without merging

2024-07-30 00:55 UTC, liferay-continuous-integration commented
Pull request has been successfully forwarded to  https://github.com/brianchandotcom/liferay-portal/pull/152769
[Console](https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest(master)/12298//consoleFull)

2024-07-30 00:59 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest(master)/12298/">test-portal-acceptance-pullrequest(master)#12298</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/12298/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-search/liferay-portal/pull/1418">liferay-search#1418</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756/build/47627297">[master] ci:test:relevant - joshuacords &gt; liferay-search - PR#1418 - 2024-07-29[16:46:21]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>47627297<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-27.liferay.com/job/publish-testray-report/26871/">publish-testray-report#26871</a><br/></div></div>