LPD-36113 Limit places where contents of connected Asset Libraries are returned in a search
liferay-search/liferay-portal pull request #1485
Opened 2024-09-19 12:55 UTC by AlmirFe

https://liferay.atlassian.net/browse/LPD-36113

2024-09-19 12:55 UTC, liferay-continuous-integration commented
The following guidelines have been set by the owner of this repository: 
- &nbsp;&nbsp;&nbsp;&nbsp;"Thank you for sending this PR to liferay-search! If you haven't already,take this opportunity to review our [pull request guidelines](https://liferay.atlassian.net/l/cp/MmMP1Sh0). For additional help,reach out via the appropriate channels listed [here](https://liferay.atlassian.net/l/cp/MmMP1Sh0#Communication%2C-point-of-contact)."

2024-09-19 12:55 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2024-09-19 12:55 UTC, AlmirFe commented
ci:test:sf

2024-09-19 12:56 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-31.liferay.com/job/test-portal-source-format/6727/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-source-format/builds/6727/jenkins-report.html">here</a>.</b></p>

2024-09-19 12:58 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/3087782d7db440cf7fc46787e38b666512ef495f">3087782d7db440cf7fc46787e38b666512ef495f</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/AlmirFe/liferay-portal/tree/LPD-36113_Limit_places_where_AL_contents_are_returned">LPD-36113_Limit_places_where_AL_contents_are_returned</a><br/>Branch GIT ID: <a href="https://github.com/AlmirFe/liferay-portal/commit/65c97a8c7a0cbe35f9932b2c37e3ac8fd986dfdd">65c97a8c7a0cbe35f9932b2c37e3ac8fd986dfdd</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-31.liferay.com/job/test-portal-source-format/6727/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-source-format/builds/6727/jenkins-report.html">here</a>.</h5></details></html>

2024-09-19 13:01 UTC, AlmirFe commented
@lipusz Could you check if after my changes there is any place in the portal where the contents belonging to an asset library should be returned and are not?

2024-09-20 00:23 UTC, joshuacords requested changes
Hi Almir,

The Collection Display Fragment doesn't seem to be working:

* Blueprints Collection Provider searches where SearchContext groupIds is populated originating from a Collection Display Fragment
* Dynamic Collection searches from a Collection Display Fragment

This and my other comment are the only issues I found.

2024-09-20 00:23 UTC, joshuacords commented on modules/dxp/apps/search-experiences/search-experiences-service/src/main/java/com/liferay/search/experiences/internal/suggestions/spi/SXPBlueprintSuggestionsContributor.java
> +				searchContext2.setAttribute(
This doesn't seem necessary, as it always seems to be called through [SuggestionResourceImpl.postSuggestionsPage](https://github.com/liferay-search/liferay-portal/pull/1485/commits/73afad5f08be45cc3c8cc51d14a36517ac3afcfe#diff-7bf4ee8557e1ad2318ae6ce78f2f8cabc844591a6b973a2a1cfc05ab79558941)

2024-09-20 00:24 UTC, joshuacords commented on modules/dxp/apps/search-experiences/search-experiences-service/src/main/java/com/liferay/search/experiences/internal/suggestions/spi/SXPBlueprintSuggestionsContributor.java
> +				searchContext2.setAttribute(
But if there's a different logic path that doesn't set the new variable but calls this method, then it should stay.

2025-01-08 14:19 UTC, closed without merging