LPD-38774: Account restriction in object not filtering properly using Custom Facets
liferay-search/liferay-portal pull request #1553
Opened 2024-11-19 16:48 UTC by felipelorenz

Ticket: https://liferay.atlassian.net/browse/LPD-38774

continuation from: https://github.com/liferay-search/liferay-portal/pull/1550

See this comment: https://github.com/liferay-search/liferay-portal/pull/1550#discussion_r1841140152

2024-11-19 16:48 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2024-11-19 16:49 UTC, felipelorenz commented
ci:test:search

2024-11-19 16:49 UTC, felipelorenz commented
ci:test:relevant

2024-11-19 16:53 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/e2347c3f89b418c60417c0e2139591b27c420f69">e2347c3f89b418c60417c0e2139591b27c420f69</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/felipelorenz/liferay-portal/tree/review_PR_gustavo_LPD-38774">review_PR_gustavo_LPD-38774</a><br/>Branch GIT ID: <a href="https://github.com/felipelorenz/liferay-portal/commit/c188990097fa08017cbba0e99ffe112c19206298">c188990097fa08017cbba0e99ffe112c19206298</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-38.liferay.com/job/test-portal-source-format/6033/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-source-format/builds/6033/jenkins-report.html">here</a>.</h5></details></html>

2024-11-19 19:20 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:search - 168 out of 180 jobs passed in 2 hours 10 minutes</h3><details><summary>Click here for more details.</summary><br/><p>This pull is eligible for <a href="https://grow.liferay.com/share/CI+liferay-continuous-integration+GitHub+Commands#General-Commands">reevaluation</a>. When this <a href="https://test-1-40.liferay.com/job/test-portal-acceptance-upstream-dxp(master)/1027">upstream build</a> has completed, using the following CI command will compare this pull request result against a more recent upstream result:<pre>ci:reevaluate:1387401_11448</pre></p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/e2347c3f89b418c60417c0e2139591b27c420f69">e2347c3f89b418c60417c0e2139591b27c420f69</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/7a1a6c1d2f2921461b329dc8951380c99c427c99">7a1a6c1d2f2921461b329dc8951380c99c427c99</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/#/project/35392/routines/590307/build/72050821">EE Development Acceptance (master) - 1026 - 2024-11-19[04:48:29]</a></p><details><summary><strong>ci:test:search - 168 out of 180 jobs PASSED</strong></summary><div><h4>12 Failed Jobs:</h4><ul><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest(master)/11448/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>functional-jboss74-mysql57<ul><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1144775/">functional-jboss74-mysql57/0/0</a></li></ul></li><li>functional-tomcat90-mysql57<ul><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/720752/">functional-tomcat90-mysql57/0/0</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/720753/">functional-tomcat90-mysql57/0/1</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/978325/">functional-tomcat90-mysql57/0/2</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/962356/">functional-tomcat90-mysql57/0/3</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/788594/"><strike>functional-tomcat90-mysql57/0/4</strike></a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/978323/">functional-tomcat90-mysql57/0/5</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1045382/">functional-tomcat90-mysql57/0/6</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/962354/">functional-tomcat90-mysql57/0/7</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/788592/">functional-tomcat90-mysql57/0/8</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/788593/">functional-tomcat90-mysql57/0/9</a></li><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/493162/">functional-tomcat90-mysql57/1/0</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1237604/">functional-tomcat90-mysql57/1/1</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1026942/">functional-tomcat90-mysql57/1/2</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1026943/">functional-tomcat90-mysql57/1/3</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1237600/">functional-tomcat90-mysql57/1/4</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1026940/">functional-tomcat90-mysql57/1/5</a></li><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/493157/">functional-tomcat90-mysql57/1/6</a></li><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/493159/">functional-tomcat90-mysql57/1/7</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1026941/">functional-tomcat90-mysql57/1/8</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1128371/">functional-tomcat90-mysql57/1/9</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1026161/"><strike>functional-tomcat90-mysql57/1/10</strike></a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/962360/">functional-tomcat90-mysql57/1/11</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1026160/">functional-tomcat90-mysql57/1/12</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1045387/">functional-tomcat90-mysql57/1/13</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/720758/">functional-tomcat90-mysql57/1/14</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1031778/">functional-tomcat90-mysql57/1/15</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1144777/">functional-tomcat90-mysql57/1/16</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1140562/">functional-tomcat90-mysql57/1/17</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1091619/">functional-tomcat90-mysql57/1/18</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1128379/">functional-tomcat90-mysql57/1/19</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1045386/">functional-tomcat90-mysql57/1/20</a></li><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/439907/">functional-tomcat90-mysql57/1/21</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/978335/">functional-tomcat90-mysql57/1/22</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/962359/">functional-tomcat90-mysql57/1/23</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1026158/">functional-tomcat90-mysql57/1/24</a></li><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/381330/">functional-tomcat90-mysql57/2/0</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1237609/">functional-tomcat90-mysql57/2/1</a></li><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/439905/">functional-tomcat90-mysql57/2/2</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1045385/">functional-tomcat90-mysql57/2/3</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/982340/">functional-tomcat90-mysql57/2/4</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/978334/">functional-tomcat90-mysql57/2/5</a></li><li><a href="https://test-1-38.lif [...]

2024-11-19 19:23 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:stable - 24 out of 24 jobs passed</h3><h3>:x: ci:test:relevant - 29 out of 34 jobs passed in 2 hours 30 minutes</h3><details><summary>Click here for more details.</summary><br/><p>This pull is eligible for <a href="https://grow.liferay.com/share/CI+liferay-continuous-integration+GitHub+Commands#General-Commands">reevaluation</a>. When this <a href="https://test-1-40.liferay.com/job/test-portal-acceptance-upstream-dxp(master)/1027">upstream build</a> has completed, using the following CI command will compare this pull request result against a more recent upstream result:<pre>ci:reevaluate:1317401_11710</pre></p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/e2347c3f89b418c60417c0e2139591b27c420f69">e2347c3f89b418c60417c0e2139591b27c420f69</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/7a1a6c1d2f2921461b329dc8951380c99c427c99">7a1a6c1d2f2921461b329dc8951380c99c427c99</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/#/project/35392/routines/590307/build/72050821">EE Development Acceptance (master) - 1026 - 2024-11-19[04:48:29]</a></p><details><summary><strong>ci:test:stable - 24 out of 24 jobs PASSED</strong></summary><details><summary><strong>24 Successful Jobs:</strong></summary><ul/></details></details><details><summary><strong>ci:test:relevant - 29 out of 34 jobs PASSED</strong></summary><div><h4>5 Failed Jobs:</h4><ul><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest(master)/11710/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>central-requirements<ul><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/788560/">central-requirements/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57_stable<ul><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/381361/">functional-smoke-tomcat90-mysql57_stable/0/0</a></li></ul></li><li>functional-upgrade-tomcat90-mysql57_stable<ul><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/381363/">functional-upgrade-tomcat90-mysql57_stable/0/0</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/788673/">functional-upgrade-tomcat90-mysql57_stable/0/1</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1237660/">functional-upgrade-tomcat90-mysql57_stable/0/2</a></li></ul></li><li>js-unit<ul><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1091589/">js-unit/0/0</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1031750/">js-unit/1/0</a></li></ul></li><li>modules-compile<ul><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/982394/">modules-compile/0/0</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1026212/">modules-compile/0/1</a></li><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/439932/">modules-compile/0/2</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1128433/">modules-compile/0/3</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/788672/">modules-compile/0/4</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1067875/">modules-compile/0/5</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/982392/">modules-compile/0/6</a></li><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/381362/">modules-compile/0/7</a></li><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/394070/">modules-compile/0/8</a></li><li><a href="https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/384720/">modules-compile/0/9</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1237659/">modules-compile/0/10</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/982393/">modules-compile/0/11</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1026211/">modules-compile/0/12</a></li></ul></li><li>modules-integration-mysql57<ul><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1067878/"><strike>modules-integration-mysql57/0/0</strike></a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1128438/"><strike>modules-integration-mysql57/0/1</strike></a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1144839/"><strike>modules-integration-mysql57/0/2</strike></a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1067874/">modules-integration-mysql57/0/3</a></li></ul></li><li>modules-integration-mysql57_stable<ul><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1067876/">modules-integration-mysql57_stable/0/0</a></li></ul></li><li>modules-semantic-versioning<ul><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/788561/">modules-semantic-versioning/0/0</a></li></ul></li><li>modules-unit<ul><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1128432/">modules-unit/0/0</a></li></ul></li><li>modules-unit_stable<ul><li><a href="https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/384719/">modules-unit_stable/0/0</a></li></ul></li><li>playwright-js-tomcat90-mysql57<ul><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/381359/"><strike>playwright-js-tomcat90-mysql57/0/0</strike></a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/982390/">playwright-js-tomcat90-mysql57/1/0</a></li><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/381360/">playwright-js-tomcat90-mysql57/2/0</a></li></ul></li><li>playwright-js-tomcat90-mysql57_stable<ul><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/381357/">playwright-js-tomcat90-mysql57_stable/0/0</a></li></ul></li><li>unit_stable<ul><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/381358/">unit_stable/0/0</a></li></ul></li></ul></div><details><summary><strong>29 Successful Jobs:</strong></summary><ul/></details></details><h5>For more details click <a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/11710/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1144839//consoleText">modules-integration-mysql57/0/2</a><ol><li><details><summary><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1144839/testReport/com.liferay.portal.search.rest.resource.v1_0.test/SearchResultResourceTest">com.liferay.portal.search.rest.resource.v1_0.test.SearchResultResourceTest</a> - <a href="https://testray.life [...]

2024-11-19 19:25 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest(master)/11448/">test-portal-acceptance-pullrequest(master)#11448</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/11448/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>search<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-search/liferay-portal/pull/1553">liferay-search#1553</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/72301281">[master] ci:test:search - felipelorenz &gt; liferay-search - PR#1553 - 2024-11-19[08:49:34]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>72301281<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-38.liferay.com/job/publish-testray-report/23647/">publish-testray-report#23647</a><br/></div></div>

2024-11-19 19:30 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest(master)/11710/">test-portal-acceptance-pullrequest(master)#11710</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/11710/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-search/liferay-portal/pull/1553">liferay-search#1553</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/72306093">[master] ci:test:relevant - felipelorenz &gt; liferay-search - PR#1553 - 2024-11-19[08:49:43]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>72306093<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-31.liferay.com/job/publish-testray-report/26971/">publish-testray-report#26971</a><br/></div></div>

2024-11-21 18:08 UTC, felipelorenz commented
ci:report:72306093

2024-11-21 18:09 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running <code>generate testray csv</code> for testrayBuildID: <b>72306093</b>.</p><p>Job Link: <a href="https://test-1-27.liferay.com/job/generate-testray-csv/306/">generate-testray-csv</a></p>

2024-11-21 18:09 UTC, liferay-continuous-integration commented
<h1>Build completed.</h1><p>Testray CSV has been generated successfully for testrayBuildID: <b>72306093</b>.</p><p>Job Link: <a href="https://test-1-27.liferay.com/job/generate-testray-csv/306/">generate-testray-csv</a></p><p>Testray CSV Link: <a href="https://test-1-27.liferay.com/userContent/jobs/generate-testray-csv/builds/306/testray-results-72306093.csv">testray-results-72306093.csv</a></p>

2024-11-21 20:25 UTC, felipelorenz commented
ci:test:relevant

2024-11-21 20:25 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest(master)/13108/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/13108/jenkins-report.html">here</a>.</b></p>

2024-11-21 22:25 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:stable - 24 out of 24 jobs passed</h3><h3>:x: ci:test:relevant - 28 out of 34 jobs passed in 1 hour 53 minutes</h3><details><summary>Click here for more details.</summary><br/><p>This pull is eligible for <a href="https://grow.liferay.com/share/CI+liferay-continuous-integration+GitHub+Commands#General-Commands">reevaluation</a>. When this <a href="https://test-1-40.liferay.com/job/test-portal-acceptance-upstream-dxp(master)/1035">upstream build</a> has completed, using the following CI command will compare this pull request result against a more recent upstream result:<pre>ci:reevaluate:1277401_13108</pre></p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/98457fab147b2d80667dfea44b015932e0ea67f3">98457fab147b2d80667dfea44b015932e0ea67f3</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/88f5c1e61324636dcb345e3358adef5e7589a5e8">88f5c1e61324636dcb345e3358adef5e7589a5e8</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/#/project/35392/routines/590307/build/74494422">EE Development Acceptance (master) - 1034 - 2024-11-21[08:41:26]</a></p><details><summary><strong>ci:test:stable - 24 out of 24 jobs PASSED</strong></summary><details><summary><strong>24 Successful Jobs:</strong></summary><ul/></details></details><details><summary><strong>ci:test:relevant - 28 out of 34 jobs PASSED</strong></summary><div><h4>6 Failed Jobs:</h4><ul><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest(master)/13108/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>central-requirements<ul><li><a href="https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/385178/">central-requirements/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57_stable<ul><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/790383/">functional-smoke-tomcat90-mysql57_stable/0/0</a></li></ul></li><li>functional-upgrade-tomcat90-mysql57_stable<ul><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1261315/">functional-upgrade-tomcat90-mysql57_stable/0/0</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1028378/">functional-upgrade-tomcat90-mysql57_stable/0/1</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1238837/">functional-upgrade-tomcat90-mysql57_stable/0/2</a></li></ul></li><li>js-unit<ul><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/440476/">js-unit/0/0</a></li><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/449601/">js-unit/1/0</a></li></ul></li><li>modules-compile<ul><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/983921/">modules-compile/0/0</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/963526/">modules-compile/0/1</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1130015/">modules-compile/0/2</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1027696/">modules-compile/0/3</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1027695/">modules-compile/0/4</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1028379/">modules-compile/0/5</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/983919/">modules-compile/0/6</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1261313/">modules-compile/0/7</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/963525/">modules-compile/0/8</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1261314/">modules-compile/0/9</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1130013/">modules-compile/0/10</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/983920/">modules-compile/0/11</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1130014/">modules-compile/0/12</a></li></ul></li><li>modules-integration-mysql57<ul><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/790387/"><strike>modules-integration-mysql57/0/0</strike></a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1033361/"><strike>modules-integration-mysql57/0/1</strike></a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1261312/"><strike>modules-integration-mysql57/0/2</strike></a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1261316/"><strike>modules-integration-mysql57/0/3</strike></a></li></ul></li><li>modules-integration-mysql57_stable<ul><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/790386/">modules-integration-mysql57_stable/0/0</a></li></ul></li><li>modules-semantic-versioning<ul><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/790380/">modules-semantic-versioning/0/0</a></li></ul></li><li>modules-unit<ul><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/790385/">modules-unit/0/0</a></li></ul></li><li>modules-unit_stable<ul><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1130012/">modules-unit_stable/0/0</a></li></ul></li><li>playwright-js-tomcat90-mysql57<ul><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1261311/"><strike>playwright-js-tomcat90-mysql57/0/0</strike></a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1027693/">playwright-js-tomcat90-mysql57/1/0</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/983917/">playwright-js-tomcat90-mysql57/2/0</a></li></ul></li><li>playwright-js-tomcat90-mysql57_stable<ul><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/983916/">playwright-js-tomcat90-mysql57_stable/0/0</a></li></ul></li><li>unit_stable<ul><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/790382/">unit_stable/0/0</a></li></ul></li></ul></div><details><summary><strong>28 Successful Jobs:</strong></summary><ul/></details></details><h5>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/13108/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1261316//consoleText">modules-integration-mysql57/0/3</a><ol><li><details><summary><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1261316/testReport/com.liferay.object.service.test/ObjectRelationshipLocalServiceTest">com.liferay.object.service.test.ObjectRelationshipLocalServiceTest</a> - <a>Failed 7 of las [...]

2024-11-21 22:33 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest(master)/13108/">test-portal-acceptance-pullrequest(master)#13108</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/13108/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-search/liferay-portal/pull/1553">liferay-search#1553</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/74656068">[master] ci:test:relevant - felipelorenz &gt; liferay-search - PR#1553 - 2024-11-21[12:25:27]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>74656068<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-27.liferay.com/job/publish-testray-report/28641/">publish-testray-report#28641</a><br/></div></div>

2024-11-25 13:11 UTC, felipelorenz commented
ci:report:74656068

2024-11-25 13:12 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running <code>generate testray csv</code> for testrayBuildID: <b>74656068</b>.</p><p>Job Link: <a href="https://test-1-37.liferay.com/job/generate-testray-csv/480/">generate-testray-csv</a></p>

2024-11-25 13:13 UTC, liferay-continuous-integration commented
<h1>Build completed.</h1><p>Testray CSV has been generated successfully for testrayBuildID: <b>74656068</b>.</p><p>Job Link: <a href="https://test-1-37.liferay.com/job/generate-testray-csv/480/">generate-testray-csv</a></p><p>Testray CSV Link: <a href="https://test-1-37.liferay.com/userContent/jobs/generate-testray-csv/builds/480/testray-results-74656068.csv">testray-results-74656068.csv</a></p>

2024-11-25 13:28 UTC, felipelorenz commented
ci:report:72301281

2024-11-25 13:29 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running <code>generate testray csv</code> for testrayBuildID: <b>72301281</b>.</p><p>Job Link: <a href="https://test-1-38.liferay.com/job/generate-testray-csv/149/">generate-testray-csv</a></p>

2024-11-25 13:30 UTC, liferay-continuous-integration commented
<h1>Build completed.</h1><p>Testray CSV has been generated successfully for testrayBuildID: <b>72301281</b>.</p><p>Job Link: <a href="https://test-1-38.liferay.com/job/generate-testray-csv/149/">generate-testray-csv</a></p><p>Testray CSV Link: <a href="https://test-1-38.liferay.com/userContent/jobs/generate-testray-csv/builds/149/testray-results-72301281.csv">testray-results-72301281.csv</a></p>

2024-11-25 20:23 UTC, marcelabc requested changes
Hi 
I finished my review. Let me know if you have questions :smile:

2024-11-25 20:23 UTC, marcelabc commented on modules/apps/object/object-service/src/test/java/com/liferay/object/internal/search/spi/model/permission/ObjectEntrySearchPermissionFilterContributorTest.java
> +				long userId)
Can you sort the parameters?

2024-11-25 20:23 UTC, marcelabc commented on modules/apps/object/object-service/src/test/java/com/liferay/object/internal/search/spi/model/permission/ObjectEntrySearchPermissionFilterContributorTest.java
> +	private void _setUpObjectEntrySearchPermissionFilterContributor(
Can you rename it to `_setUpSearchPermissionCheckerConfiguration()` ?

2024-11-25 20:23 UTC, marcelabc commented on modules/apps/object/object-service/src/test/java/com/liferay/object/internal/search/spi/model/permission/ObjectEntrySearchPermissionFilterContributorTest.java
> +			objectEntrySearchPermissionFilterContributor, userId);
Can you sort the setUp methods?

2024-11-25 20:23 UTC, marcelabc commented on modules/apps/object/object-service/src/test/java/com/liferay/object/internal/search/spi/model/permission/ObjectEntrySearchPermissionFilterContributorTest.java
> +		List<AccountEntryUserRel> accountEntryRelList = Arrays.asList(
Rename it to `AccountEntryRels`

2024-11-25 20:23 UTC, marcelabc commented on modules/apps/object/object-service/src/test/java/com/liferay/object/internal/search/spi/model/permission/ObjectEntrySearchPermissionFilterContributorTest.java
> +			_createAccountEntryRel(activeAccountEntryId, false));
sort:
```
_createAccountEntryRel(activeAccountEntryId, false)
_createAccountEntryRel(inactiveAccountEntryId, true)
```

2024-11-26 13:25 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-7.liferay.com/job/test-portal-source-format/6333/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-7.liferay.com/userContent/jobs/test-portal-source-format/builds/6333/jenkins-report.html">here</a>.</b></p>

2024-11-26 13:28 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/80ec2855f6e41bb82ba0125a7b7bef558743dfcf">80ec2855f6e41bb82ba0125a7b7bef558743dfcf</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/felipelorenz/liferay-portal/tree/review_PR_gustavo_LPD-38774">review_PR_gustavo_LPD-38774</a><br/>Branch GIT ID: <a href="https://github.com/felipelorenz/liferay-portal/commit/074a78b0f95ac5cb9c8d6098903b6df49fcfa979">074a78b0f95ac5cb9c8d6098903b6df49fcfa979</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-7.liferay.com/job/test-portal-source-format/6333/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-7.liferay.com/userContent/jobs/test-portal-source-format/builds/6333/jenkins-report.html">here</a>.</h5></details></html>

2024-11-26 13:45 UTC, felipelorenz commented
Hi @marcelabc! I made the changes you requested me, let me know if have anything else to change, or if its good to you.

2024-11-26 16:13 UTC, marcelabc requested changes
Hi 
I finished my review. Let me know if you have questions :smile:

2024-11-26 16:13 UTC, marcelabc commented on modules/apps/object/object-service/src/test/java/com/liferay/object/internal/search/spi/model/permission/ObjectEntrySearchPermissionFilterContributorTest.java
> +		List<AccountEntryUserRel> accountEntryRels = Arrays.asList(
Can you rename it to `AccountEntryUserRels`? ( I think you miss the AccountEntry**User**Rels)

2024-11-26 16:13 UTC, marcelabc commented on modules/apps/object/object-service/src/test/java/com/liferay/object/internal/search/spi/model/permission/ObjectEntrySearchPermissionFilterContributorTest.java
> +	private AccountEntryUserRel _createAccountEntryRel(
Rename it to _createAccountEntry**User**Rel

2024-11-26 16:13 UTC, marcelabc commented on modules/apps/object/object-service/src/test/java/com/liferay/object/internal/search/spi/model/permission/ObjectEntrySearchPermissionFilterContributorTest.java
> +		return accountEntryUserRel;
I would organize this method like this:
```
AccountEntry accountEntry = Mockito.mock(AccountEntry.class);

Mockito.when(
	accountEntry.getAccountEntryId()
).thenReturn(
	accountEntryId
);

Mockito.when(
	accountEntry.isInactive()
).thenReturn(
	inactive
);

AccountEntryUserRel accountEntryUserRel = Mockito.mock(
	AccountEntryUserRel.class);

Mockito.when(
	accountEntryUserRel.getAccountEntry()
).thenReturn(
	accountEntry
);

return accountEntryUserRel;
```

2024-11-26 16:13 UTC, marcelabc commented on modules/apps/object/object-service/src/test/java/com/liferay/object/internal/search/spi/model/permission/ObjectEntrySearchPermissionFilterContributorTest.java
> +	private void _setUpAccountEntryRels(
Can you rename it to _setUpAccountEntry**User**Rels ?

2024-11-26 17:58 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-39.liferay.com/job/test-portal-source-format/7041/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-source-format/builds/7041/jenkins-report.html">here</a>.</b></p>

2024-11-26 18:01 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/80ec2855f6e41bb82ba0125a7b7bef558743dfcf">80ec2855f6e41bb82ba0125a7b7bef558743dfcf</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/felipelorenz/liferay-portal/tree/review_PR_gustavo_LPD-38774">review_PR_gustavo_LPD-38774</a><br/>Branch GIT ID: <a href="https://github.com/felipelorenz/liferay-portal/commit/a38ce0175f2a012f67f71b7447d8cc0919c78a4f">a38ce0175f2a012f67f71b7447d8cc0919c78a4f</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-39.liferay.com/job/test-portal-source-format/7041/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-source-format/builds/7041/jenkins-report.html">here</a>.</h5></details></html>

2024-11-26 18:03 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-39.liferay.com/job/test-portal-source-format/7041/">test-portal-source-format#7041</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-source-format/builds/7041/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-search/liferay-portal/pull/1553">liferay-search#1553</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/77858665">[master] ci:test:sf - felipelorenz &gt; liferay-search - PR#1553 - 2024-11-26[09:57:25]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>77858665<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-39.liferay.com/job/publish-testray-report/25698/">publish-testray-report#25698</a><br/></div></div>

2024-11-26 20:43 UTC, felipelorenz commented
Hi @marcelabc! I made the changes you requested me, let me know if have anything else to change, or if its good to you.

2024-11-28 19:32 UTC, marcelabc approved these changes
LGTM 🎉
@felipelorenz thank you for your work!

2025-02-27 17:44 UTC, closed without merging