LPS-172173 portal-search-web: Hide blueprints suggestions when Solr
liferay-search/liferay-portal pull request #727
Opened 2023-01-11 01:07 UTC by oliv-yu

https://issues.liferay.com/browse/LPS-172173 - [FE] Search Bar widget configuration: Hide Blueprints Suggestions Contributor

Some notes:
- In CE or Solr, there is the option to add/delete only one contributor, the basic one. 
- Several utils were created to address the cleaning up of the suggestions configuration, which parses and filters out blueprints if needed.
- Condition of whether Solr is being used relies on `SearchCapabilities`'s `isSearchExperiencesSupported`

Probably would cause a merge conflict with https://github.com/liferay-search/liferay-portal/pull/726 so I'll resend 726 after this is reviewed!

2023-01-11 01:07 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**search**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

2023-01-11 01:09 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-26.liferay.com/job/test-portal-source-format/4453/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-source-format/builds/4453/jenkins-report.html">here</a>.</b></p>

2023-01-11 01:11 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/ffaf63c35bea589c743101c834914c4829f43ef5">ffaf63c35bea589c743101c834914c4829f43ef5</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/oliv-yu/liferay-portal/tree/LPS-172173-hide-blueprints-contributors">LPS-172173-hide-blueprints-contributors</a><br/>Branch GIT ID: <a href="https://github.com/oliv-yu/liferay-portal/commit/59d008395d6c769f3ae5571a32451ad5f82e7965">59d008395d6c769f3ae5571a32451ad5f82e7965</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-26.liferay.com/job/test-portal-source-format/4453/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-source-format/builds/4453/jenkins-report.html">here</a>.</h5></details></html>

2023-01-11 01:20 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-26.liferay.com/job/test-portal-source-format/4453/">test-portal-source-format#4453</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-source-format/builds/4453/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-search/liferay-portal/pull/727">liferay-search#727</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2155872942">[master] ci:test:sf - oliv-yu &gt; liferay-search - PR#727 - 2023-01-10[17:07:49]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-26.liferay.com/job/publish-testray-report/16690/">publish-testray-report#16690</a><br/></div></div>

2023-01-11 02:27 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>search</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest(master)/6114/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/6114/jenkins-report.html">here</a>.</b></p>

2023-01-11 03:57 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:search - 136 out of 155 jobs passed in 1 hour 30 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/ffaf63c35bea589c743101c834914c4829f43ef5">ffaf63c35bea589c743101c834914c4829f43ef5</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/ffaf63c35bea589c743101c834914c4829f43ef5">ffaf63c35bea589c743101c834914c4829f43ef5</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2154766853">EE Development Acceptance (master) - 4179 - 2023-01-10[05:57:32]</a></p><details><summary><strong>ci:test:search - 136 out of 155 jobs PASSED</strong></summary><div><h4>19 Failed Jobs:</h4><ul><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest(master)/6114/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>central-requirements-jdk8<ul><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/133893/">central-requirements-jdk8/0/0</a></li></ul></li><li>functional-tomcat90-mysql57-jdk11_open<ul><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/147865/">functional-tomcat90-mysql57-jdk11_open/0/0</a></li><li><a href="https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/150224/">functional-tomcat90-mysql57-jdk11_open/0/1</a></li></ul></li><li>functional-tomcat90-mysql57-jdk8<ul><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/223925/">functional-tomcat90-mysql57-jdk8/0/0</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/376169/">functional-tomcat90-mysql57-jdk8/0/1</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/383388/">functional-tomcat90-mysql57-jdk8/0/2</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/339534/"><strike>functional-tomcat90-mysql57-jdk8/0/3</strike></a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/223926/">functional-tomcat90-mysql57-jdk8/0/4</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/368980/">functional-tomcat90-mysql57-jdk8/0/5</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/391608/">functional-tomcat90-mysql57-jdk8/0/6</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/368981/">functional-tomcat90-mysql57-jdk8/0/7</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/391609/">functional-tomcat90-mysql57-jdk8/0/8</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/337652/">functional-tomcat90-mysql57-jdk8/0/9</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/337649/">functional-tomcat90-mysql57-jdk8/0/10</a></li><li><a href="https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/146680/">functional-tomcat90-mysql57-jdk8/1/0</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/415222/">functional-tomcat90-mysql57-jdk8/1/1</a></li><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/137764/">functional-tomcat90-mysql57-jdk8/1/2</a></li><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/151286/">functional-tomcat90-mysql57-jdk8/1/3</a></li><li><a href="https://test-1-15.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/147611/"><strike>functional-tomcat90-mysql57-jdk8/1/4</strike></a></li><li><a href="https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/147815/">functional-tomcat90-mysql57-jdk8/1/5</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/415223/">functional-tomcat90-mysql57-jdk8/1/6</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/337650/">functional-tomcat90-mysql57-jdk8/1/7</a></li><li><a href="https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/150223/">functional-tomcat90-mysql57-jdk8/1/8</a></li><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/147866/">functional-tomcat90-mysql57-jdk8/1/9</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/173969/">functional-tomcat90-mysql57-jdk8/1/10</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/366153/"><strike>functional-tomcat90-mysql57-jdk8/1/11</strike></a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/348666/"><strike>functional-tomcat90-mysql57-jdk8/1/12</strike></a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/337655/"><strike>functional-tomcat90-mysql57-jdk8/1/13</strike></a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/339537/">functional-tomcat90-mysql57-jdk8/1/14</a></li><li><a href="https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/147006/">functional-tomcat90-mysql57-jdk8/1/15</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/415228/">functional-tomcat90-mysql57-jdk8/1/16</a></li><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/144264/">functional-tomcat90-mysql57-jdk8/1/17</a></li><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/144265/">functional-tomcat90-mysql57-jdk8/1/18</a></li><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/136418/">functional-tomcat90-mysql57-jdk8/1/19</a></li><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/144266/">functional-tomcat90-mysql57-jdk8/1/20</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/394471/">functional-tomcat90-mysql57-jdk8/1/21</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/173966/">functional-tomcat90-mysql57-jdk8/1/22</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/223928/">functional-tomcat90-mysql57-jdk8/1/23</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/337654/">functional-tomcat90-mysql57-jdk8/1/24</a></li><li><a href="https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/120570/">functional-tomcat90-mysql57-jdk8/2/0</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/312412/">functional-tomcat90-mysql57-jdk8/2/1</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/383389/">functional-tomcat90-mysql57-jdk8/2/2</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/391613/">functional-tomcat90-mysql57-jdk8/2/3</a></li><li><a href="https:// [...]

2023-01-11 04:05 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest(master)/6114/">test-portal-acceptance-pullrequest(master)#6114</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/6114/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>search<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-search/liferay-portal/pull/727">liferay-search#727</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2155979737">[master] ci:test:search - oliv-yu &gt; liferay-search - PR#727 - 2023-01-10[18:27:03]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-29.liferay.com/job/publish-testray-report/14794/">publish-testray-report#14794</a><br/></div></div>

2023-01-11 20:11 UTC, oliv-yu commented
It looks like the test failures are already known, but let me know what you think! According to Tibor, testing on Solr had worked. Also with the command `ant -f build-test-solr.xml start-solr` it looked like it filtered out blueprints for me.

2023-01-12 00:00 UTC, thektan requested changes
Can you separate the backend changes into another commit? The backend commit would read something like "Add isSearchExperiencesSupported to SearchBarPortletDisplayContext".

You can run `ci:forward` on this once you make this change. Thanks!

2023-01-12 00:42 UTC, oliv-yu commented
ci:forward

2023-01-12 00:42 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

The pull request will automatically be forwarded to the user `brianchandotcom` if the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2023-01-12 00:42 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest(master)/7907/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/7907/jenkins-report.html">here</a>.</b></p>

2023-01-12 00:44 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-37.liferay.com/job/test-portal-source-format/4748/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/4748/jenkins-report.html">here</a>.</b></p>

2023-01-12 00:46 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/045dfcd7cf0f5630008e30b11e4694570adea96a">045dfcd7cf0f5630008e30b11e4694570adea96a</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/oliv-yu/liferay-portal/tree/LPS-172173-hide-blueprints-contributors">LPS-172173-hide-blueprints-contributors</a><br/>Branch GIT ID: <a href="https://github.com/oliv-yu/liferay-portal/commit/c60aebe034108f2a6f06fe8a31c3ac59dedcbe82">c60aebe034108f2a6f06fe8a31c3ac59dedcbe82</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-37.liferay.com/job/test-portal-source-format/4748/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/4748/jenkins-report.html">here</a>.</h5></details></html>

2023-01-12 00:48 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-37.liferay.com/job/test-portal-source-format/4748/">test-portal-source-format#4748</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/4748/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-search/liferay-portal/pull/727">liferay-search#727</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2158239852">[master] ci:test:sf - oliv-yu &gt; liferay-search - PR#727 - 2023-01-11[16:42:30]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-37.liferay.com/job/publish-testray-report/18161/">publish-testray-report#18161</a><br/></div></div>

2023-01-12 01:16 UTC, thektan approved these changes

2023-01-12 02:08 UTC, liferay-continuous-integration commented
Pull request has been successfully forwarded to https://github.com/brianchandotcom/liferay-portal/pull/128640
[Console](https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest(master)/7907//consoleFull)

2023-01-12 02:08 UTC, closed without merging