LPS-171159 search-experiences-web: Add Logic to return specific error when user try to import a duplicated ERC
liferay-search/liferay-portal pull request #783
Opened 2023-02-08 21:33 UTC by gustavolimav

2023-02-08 21:33 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**search**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

2023-02-08 22:30 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>search</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest(master)/8798/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/8798/jenkins-report.html">here</a>.</b></p>

2023-02-08 22:31 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:search - 0 out of 1 jobs passed in 2 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/0c4b8ffd1ce971d6402347f0aa5b8a1b217f31b8">0c4b8ffd1ce971d6402347f0aa5b8a1b217f31b8</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/d8769dbc1d0dc79fc8ed0957b685e3c0be9e265a">d8769dbc1d0dc79fc8ed0957b685e3c0be9e265a</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2190073101">EE Development Acceptance (master) - 4266 - 2023-02-08[07:39:56]</a></p><details><summary><strong>ci:test:search - 0 out of 1 jobs PASSED</strong></summary><div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest(master)/8798/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li></ul></div></details><h5>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/8798/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><h5><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest(master)/8798/">test-portal-acceptance-pullrequest(master)</a></h5><div><h6>Job Results:</h6><p>0 Jobs Passed.<br/>1 Job Failed.</p></div><div><p>The sender branch SHA could not be found on <strong><a href="https://github.com/liferay-search/liferay-portal/pull/783">gustavolimav/LPS-171159_blueprint_element_export_import</a></strong>. The sender branch may have been force pushed or deleted after the pull request test was initiated.</p><pre>fatal: Not a valid branch point: 'b7568c40fe1582dcfcff976c2ca965ad2109e667'.</pre></div></div></li></ol><h4>For upstream results, click <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)">here</a>.</h4></details></html><h5>Test bundle downloads:</h5><ul><li><a href="https://files.liferay.com/private/bundles/test-1-37/jobs/test-portal-acceptance-pullrequest(master)/builds/8798/liferay-portal-bundle-tomcat.tar.gz">liferay-portal-bundle-tomcat.tar.gz</a> (mirrors: <a href="http://mirrors.dlc.liferay.com/files.liferay.com/private/bundles/test-1-37/jobs/test-portal-acceptance-pullrequest(master)/builds/8798/liferay-portal-bundle-tomcat.tar.gz">dlc</a>, <a href="http://mirrors.lax.liferay.com/files.liferay.com/private/bundles/test-1-37/jobs/test-portal-acceptance-pullrequest(master)/builds/8798/liferay-portal-bundle-tomcat.tar.gz">lax</a>)</li></ul>

2023-02-09 01:03 UTC, joshuacords commented
Hi @gustavolimav, this looks pretty good - could you explain how the DuplicateSXPBlueprintExternalReferenceCodeException gets checked for and then thrown? I'm not to familiar with ExceptionMappers.

2023-02-09 01:04 UTC, joshuacords commented
ci:test:sf

2023-02-09 01:04 UTC, joshuacords commented
ci:test:search

2023-02-09 01:04 UTC, joshuacords commented
ci:test:relevant

2023-02-09 01:07 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-18.liferay.com/job/test-portal-source-format/6702/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-18.liferay.com/userContent/jobs/test-portal-source-format/builds/6702/jenkins-report.html">here</a>.</b></p>

2023-02-09 01:09 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/0c4b8ffd1ce971d6402347f0aa5b8a1b217f31b8">0c4b8ffd1ce971d6402347f0aa5b8a1b217f31b8</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/gustavolimav/liferay-portal/tree/LPS-171159_blueprint_element_export_import">LPS-171159_blueprint_element_export_import</a><br/>Branch GIT ID: <a href="https://github.com/gustavolimav/liferay-portal/commit/39953be06cef5c57086badcac07efeb98edbaf58">39953be06cef5c57086badcac07efeb98edbaf58</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-18.liferay.com/job/test-portal-source-format/6702/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-18.liferay.com/userContent/jobs/test-portal-source-format/builds/6702/jenkins-report.html">here</a>.</h5><pre>     [java] java.lang.Exception: Found 10 formatting issues:
     [java] 1: Missing copyright, see https://github.com/liferay/liferay-portal/blob/master/modules/util/source-formatter/src/main/resources/documentation/check/copyright_check.markdown: ./modules/dxp/apps/search-experiences/search-experiences-rest-impl/src/main/java/com/liferay/search/experiences/rest/internal/jaxrs/exception/DuplicateSXPBlueprintExternalReferenceCodeExceptionMapper.java (SourceCheck:CopyrightCheck)
     [java] 2: Missing author: ./modules/dxp/apps/search-experiences/search-experiences-rest-impl/src/main/java/com/liferay/search/experiences/rest/internal/jaxrs/exception/DuplicateSXPBlueprintExternalReferenceCodeExceptionMapper.java 11 (Checkstyle:MissingAuthorCheck)
     [java] 3: Rename exception variable 'exception' to 'duplicateSXPBlueprintExternalReferenceCodeException': ./modules/dxp/apps/search-experiences/search-experiences-rest-impl/src/main/java/com/liferay/search/experiences/rest/internal/jaxrs/exception/DuplicateSXPBlueprintExternalReferenceCodeExceptionMapper.java 23 (Checkstyle:ExceptionVariableNameCheck)
     [java] 4: Rename variable 'exception' to 'duplicateSXPBlueprintExternalReferenceCodeException': ./modules/dxp/apps/search-experiences/search-experiences-rest-impl/src/main/java/com/liferay/search/experiences/rest/internal/jaxrs/exception/DuplicateSXPBlueprintExternalReferenceCodeExceptionMapper.java 23 (Checkstyle:VariableNameCheck)
     [java] 5: Missing copyright, see https://github.com/liferay/liferay-portal/blob/master/modules/util/source-formatter/src/main/resources/documentation/check/copyright_check.markdown: ./modules/dxp/apps/search-experiences/search-experiences-rest-impl/src/main/java/com/liferay/search/experiences/rest/internal/jaxrs/exception/DuplicateSXPElementExternalReferenceCodeExceptionMapper.java (SourceCheck:CopyrightCheck)
     [java] 6: Missing author: ./modules/dxp/apps/search-experiences/search-experiences-rest-impl/src/main/java/com/liferay/search/experiences/rest/internal/jaxrs/exception/DuplicateSXPElementExternalReferenceCodeExceptionMapper.java 11 (Checkstyle:MissingAuthorCheck)
     [java] 7: Rename exception variable 'exception' to 'duplicateSXPElementExternalReferenceCodeException': ./modules/dxp/apps/search-experiences/search-experiences-rest-impl/src/main/java/com/liferay/search/experiences/rest/internal/jaxrs/exception/DuplicateSXPElementExternalReferenceCodeExceptionMapper.java 23 (Checkstyle:ExceptionVariableNameCheck)</pre></details></html>

2023-02-09 01:10 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>search</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest(master)/8160/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/8160/jenkins-report.html">here</a>.</b></p>

2023-02-09 01:11 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest(master)/3470/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-34.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/3470/jenkins-report.html">here</a>.</b></p>

2023-02-09 01:18 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-18.liferay.com/job/test-portal-source-format/6702/">test-portal-source-format#6702</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-18.liferay.com/userContent/jobs/test-portal-source-format/builds/6702/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-search/liferay-portal/pull/783">liferay-search#783</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2190450871">[master] ci:test:sf - gustavolimav &gt; liferay-search - PR#783 - 2023-02-08[17:05:12]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-18.liferay.com/job/publish-testray-report/3425/">publish-testray-report#3425</a><br/></div></div>

2023-02-09 01:43 UTC, thektan requested changes
Just noticed a small typo. Frontend changes look good 👍

2023-02-09 01:43 UTC, thektan commented on modules/apps/portal-language/portal-language-lang/src/main/resources/content/Language.properties
> +unable-to-import-element-with-the-same-external-reference-code-with-the-same-as-an-existing-blueprint=Unable to import element with the same external reference code as an existing blueprint.
Small typo.

```suggestion
unable-to-import-blueprint-with-the-same-external-reference-code-with-the-same-as-an-existing-blueprint=Unable to import blueprint with the same external reference code as an existing blueprint.
```

2023-02-09 03:04 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:stable - 28 out of 28 jobs passed</h3><h3>:x: ci:test:relevant - 112 out of 119 jobs passed in 1 hour 54 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/0c4b8ffd1ce971d6402347f0aa5b8a1b217f31b8">0c4b8ffd1ce971d6402347f0aa5b8a1b217f31b8</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/0c4b8ffd1ce971d6402347f0aa5b8a1b217f31b8">0c4b8ffd1ce971d6402347f0aa5b8a1b217f31b8</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2190556609">EE Development Acceptance (master) - 4268 - 2023-02-08[15:10:03]</a></p><details><summary><strong>ci:test:stable - 28 out of 28 jobs PASSED</strong></summary><details><summary><strong>28 Successful Jobs:</strong></summary><ul/></details></details><details><summary><strong>ci:test:relevant - 112 out of 119 jobs PASSED</strong></summary><div><h4>7 Failed Jobs:</h4><ul><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest(master)/3470/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>central-requirements-jdk8<ul><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/150540/">central-requirements-jdk8/0/0</a></li></ul></li><li>empty-osgi-core-dir-jdk8<ul><li><a href="https://test-1-15.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/160342/">empty-osgi-core-dir-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57-jdk11_open<ul><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/214413/">functional-smoke-tomcat90-mysql57-jdk11_open/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57-jdk8_stable<ul><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/373788/">functional-smoke-tomcat90-mysql57-jdk8_stable/0/0</a></li></ul></li><li>functional-smoke-wildfly180-mariadb104-jdk8<ul><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/373786/">functional-smoke-wildfly180-mariadb104-jdk8/0/0</a></li></ul></li><li>functional-smoke-wildfly180-mariadb106-jdk8<ul><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/384152/">functional-smoke-wildfly180-mariadb106-jdk8/0/0</a></li></ul></li><li>functional-tomcat90-mysql57-chrome100-jdk8<ul><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/214420/">functional-tomcat90-mysql57-chrome100-jdk8/0/0</a></li><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/156750/">functional-tomcat90-mysql57-chrome100-jdk8/0/1</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/459236/"><strike>functional-tomcat90-mysql57-chrome100-jdk8/0/2</strike></a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/377365/">functional-tomcat90-mysql57-chrome100-jdk8/0/3</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/384161/"><strike>functional-tomcat90-mysql57-chrome100-jdk8/0/4</strike></a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/403452/">functional-tomcat90-mysql57-chrome100-jdk8/0/5</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/403453/">functional-tomcat90-mysql57-chrome100-jdk8/0/6</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/347502/">functional-tomcat90-mysql57-chrome100-jdk8/0/7</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/347503/">functional-tomcat90-mysql57-chrome100-jdk8/0/8</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/431841/">functional-tomcat90-mysql57-chrome100-jdk8/0/9</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/347504/">functional-tomcat90-mysql57-chrome100-jdk8/0/10</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/431843/">functional-tomcat90-mysql57-chrome100-jdk8/0/11</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/373785/">functional-tomcat90-mysql57-chrome100-jdk8/0/12</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/403455/">functional-tomcat90-mysql57-chrome100-jdk8/0/13</a></li><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/151204/">functional-tomcat90-mysql57-chrome100-jdk8/0/14</a></li><li><a href="https://test-1-18.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/162239/">functional-tomcat90-mysql57-chrome100-jdk8/0/15</a></li><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/151205/">functional-tomcat90-mysql57-chrome100-jdk8/0/16</a></li><li><a href="https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/151627/">functional-tomcat90-mysql57-chrome100-jdk8/0/17</a></li><li><a href="https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/158989/">functional-tomcat90-mysql57-chrome100-jdk8/0/18</a></li><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/151203/">functional-tomcat90-mysql57-chrome100-jdk8/0/19</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/459235/">functional-tomcat90-mysql57-chrome100-jdk8/0/20</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/377364/">functional-tomcat90-mysql57-chrome100-jdk8/0/21</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/384159/">functional-tomcat90-mysql57-chrome100-jdk8/0/22</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/347501/">functional-tomcat90-mysql57-chrome100-jdk8/0/23</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/214419/">functional-tomcat90-mysql57-chrome100-jdk8/0/24</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/459230/">functional-tomcat90-mysql57-chrome100-jdk8/1/0</a></li></ul></li><li>functional-upgrade-tomcat90-mysql57-jdk8<ul><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/402366/">functional-upgrade-tomcat90-mysql57-jdk8/0/0</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/347500/">functional-upgrade-tomcat90-mysql57-jdk8/0/1</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/347498/">functional-upgrade-tomcat90-mysql57-jdk8/0/2</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/347499/">functional-upgrade-tomcat90-mysql57-jdk8/0/3</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/214418/">functional-upgrade-tomcat90-mysql57-jdk8/0/4</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/350405/">functional-upgrad [...]

2023-02-09 03:09 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest(master)/3470/">test-portal-acceptance-pullrequest(master)#3470</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-34.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/3470/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-search/liferay-portal/pull/783">liferay-search#783</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2190599104">[master] ci:test:relevant - gustavolimav &gt; liferay-search - PR#783 - 2023-02-08[17:10:30]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-34.liferay.com/job/publish-testray-report/8396/">publish-testray-report#8396</a><br/></div></div>

2023-02-09 03:29 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:search - 131 out of 153 jobs passed in 2 hours 19 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/0c4b8ffd1ce971d6402347f0aa5b8a1b217f31b8">0c4b8ffd1ce971d6402347f0aa5b8a1b217f31b8</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/0c4b8ffd1ce971d6402347f0aa5b8a1b217f31b8">0c4b8ffd1ce971d6402347f0aa5b8a1b217f31b8</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2190556609">EE Development Acceptance (master) - 4268 - 2023-02-08[15:10:03]</a></p><details><summary><strong>ci:test:search - 131 out of 153 jobs PASSED</strong></summary><div><h4>22 Failed Jobs:</h4><ul><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest(master)/8160/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>central-requirements-jdk8<ul><li><a href="https://test-1-12.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/165408/">central-requirements-jdk8/0/0</a></li></ul></li><li>functional-tomcat90-mysql57-jdk11_open<ul><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/384140/">functional-tomcat90-mysql57-jdk11_open/0/0</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/214396/">functional-tomcat90-mysql57-jdk11_open/0/1</a></li></ul></li><li>functional-tomcat90-mysql57-jdk8<ul><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/373772/">functional-tomcat90-mysql57-jdk8/0/0</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/377351/">functional-tomcat90-mysql57-jdk8/0/1</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/350396/"><strike>functional-tomcat90-mysql57-jdk8/0/2</strike></a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/384144/">functional-tomcat90-mysql57-jdk8/0/3</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/415536/">functional-tomcat90-mysql57-jdk8/0/4</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/416586/">functional-tomcat90-mysql57-jdk8/0/5</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/416585/">functional-tomcat90-mysql57-jdk8/0/6</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/384145/">functional-tomcat90-mysql57-jdk8/0/7</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/459219/">functional-tomcat90-mysql57-jdk8/0/8</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/214403/">functional-tomcat90-mysql57-jdk8/0/9</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/214397/">functional-tomcat90-mysql57-jdk8/0/10</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/214399/">functional-tomcat90-mysql57-jdk8/1/0</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/459214/">functional-tomcat90-mysql57-jdk8/1/1</a></li><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/156744/">functional-tomcat90-mysql57-jdk8/1/2</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/384141/">functional-tomcat90-mysql57-jdk8/1/3</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/377348/">functional-tomcat90-mysql57-jdk8/1/4</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/459215/">functional-tomcat90-mysql57-jdk8/1/5</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/377349/">functional-tomcat90-mysql57-jdk8/1/6</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/459216/">functional-tomcat90-mysql57-jdk8/1/7</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/214400/">functional-tomcat90-mysql57-jdk8/1/8</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/403433/">functional-tomcat90-mysql57-jdk8/1/9</a></li><li><a href="https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/150913/">functional-tomcat90-mysql57-jdk8/1/10</a></li><li><a href="https://test-1-23.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/138816/">functional-tomcat90-mysql57-jdk8/1/11</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/350399/">functional-tomcat90-mysql57-jdk8/1/12</a></li><li><a href="https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/135491/">functional-tomcat90-mysql57-jdk8/1/13</a></li><li><a href="https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/139747/">functional-tomcat90-mysql57-jdk8/1/14</a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/165003/">functional-tomcat90-mysql57-jdk8/1/15</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/256201/">functional-tomcat90-mysql57-jdk8/1/16</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/403437/">functional-tomcat90-mysql57-jdk8/1/17</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/347489/">functional-tomcat90-mysql57-jdk8/1/18</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/377352/">functional-tomcat90-mysql57-jdk8/1/19</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/431830/">functional-tomcat90-mysql57-jdk8/1/20</a></li><li><a href="https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/158983/">functional-tomcat90-mysql57-jdk8/1/21</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/416587/">functional-tomcat90-mysql57-jdk8/1/22</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/415537/">functional-tomcat90-mysql57-jdk8/1/23</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/438090/">functional-tomcat90-mysql57-jdk8/1/24</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/459221/">functional-tomcat90-mysql57-jdk8/2/0</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/403441/">functional-tomcat90-mysql57-jdk8/2/1</a></li><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/127807/">functional-tomcat90-mysql57-jdk8/2/2</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/402355/"><strike>functional-tomcat90-mysql57-jdk8/2/3</strike></a></li><li><a href="https://test-1-21.liferay.com/job/test-portal-acceptanc [...]

2023-02-09 03:38 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest(master)/8160/">test-portal-acceptance-pullrequest(master)#8160</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/8160/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>search<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-search/liferay-portal/pull/783">liferay-search#783</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2190613172">[master] ci:test:search - gustavolimav &gt; liferay-search - PR#783 - 2023-02-08[17:10:31]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-32.liferay.com/job/publish-testray-report/20145/">publish-testray-report#20145</a><br/></div></div>

2023-02-09 11:56 UTC, gustavolimav commented
ci:test:sf

2023-02-09 12:15 UTC, gustavolimav commented
> Hi @gustavolimav, this looks pretty good - could you explain how the DuplicateSXPBlueprintExternalReferenceCodeException gets checked for and then thrown? I'm not to familiar with ExceptionMappers.

The Exception throws [here](https://github.com/liferay/liferay-portal/blob/6f0f6d0eff98062915dc45990f1847d8d2ec0447/modules/dxp/apps/search-experiences/search-experiences-service/src/main/java/com/liferay/search/experiences/service/impl/SXPElementLocalServiceImpl.java#L202) and because it is registred in OSGI with `service = ExceptionMapper.class` when some Exception throws it will check if the type is registered and call the ExceptionMapper file. I just needed to implement `getProblem` to return the message and status that I want, and implement `isSanitize` to avoid the base class sanitizing it and remove the title from the response.

Other details about EceptionMappers I read here (Actually I had forgot to put `@Provider`):
https://www.ibm.com/docs/en/was-nd/8.5.5?topic=applications-defining-exception-mappers-resource-exceptions-errors
https://dennis-xlc.gitbooks.io/restful-java-with-jax-rs-2-0-2rd-edition/content/en/part1/chapter7/exception_handling.html

2023-02-09 12:16 UTC, gustavolimav commented
ci:test:sf

2023-02-09 12:26 UTC, gustavolimav commented
ci:test:sf

2023-02-09 12:28 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-25.liferay.com/job/test-portal-source-format/4017/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/4017/jenkins-report.html">here</a>.</b></p>

2023-02-09 12:31 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/b38777bdf00d43dcb9d978655717a3c5886179e1">b38777bdf00d43dcb9d978655717a3c5886179e1</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/gustavolimav/liferay-portal/tree/LPS-171159_blueprint_element_export_import">LPS-171159_blueprint_element_export_import</a><br/>Branch GIT ID: <a href="https://github.com/gustavolimav/liferay-portal/commit/f4fd2bfd77a12ddaa77297b7ea280d73930ac125">f4fd2bfd77a12ddaa77297b7ea280d73930ac125</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-25.liferay.com/job/test-portal-source-format/4017/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/4017/jenkins-report.html">here</a>.</h5></details></html>

2023-02-09 12:33 UTC, gustavolimav commented
ci:test:search

2023-02-09 12:33 UTC, gustavolimav commented
ci:test:relevant

2023-02-09 12:34 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-25.liferay.com/job/test-portal-source-format/4017/">test-portal-source-format#4017</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/4017/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-search/liferay-portal/pull/783">liferay-search#783</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2191157917">[master] ci:test:sf - gustavolimav &gt; liferay-search - PR#783 - 2023-02-09[04:26:34]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-25.liferay.com/job/publish-testray-report/15047/">publish-testray-report#15047</a><br/></div></div>

2023-02-09 12:35 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-6.liferay.com/job/test-portal-source-format/6305/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-6.liferay.com/userContent/jobs/test-portal-source-format/builds/6305/jenkins-report.html">here</a>.</b></p>

2023-02-09 12:38 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/b38777bdf00d43dcb9d978655717a3c5886179e1">b38777bdf00d43dcb9d978655717a3c5886179e1</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/gustavolimav/liferay-portal/tree/LPS-171159_blueprint_element_export_import">LPS-171159_blueprint_element_export_import</a><br/>Branch GIT ID: <a href="https://github.com/gustavolimav/liferay-portal/commit/f4fd2bfd77a12ddaa77297b7ea280d73930ac125">f4fd2bfd77a12ddaa77297b7ea280d73930ac125</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-6.liferay.com/job/test-portal-source-format/6305/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-6.liferay.com/userContent/jobs/test-portal-source-format/builds/6305/jenkins-report.html">here</a>.</h5></details></html>

2023-02-09 12:44 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-12.liferay.com/job/test-portal-source-format/4699/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-12.liferay.com/userContent/jobs/test-portal-source-format/builds/4699/jenkins-report.html">here</a>.</b></p>

2023-02-09 12:47 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/b38777bdf00d43dcb9d978655717a3c5886179e1">b38777bdf00d43dcb9d978655717a3c5886179e1</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/gustavolimav/liferay-portal/tree/LPS-171159_blueprint_element_export_import">LPS-171159_blueprint_element_export_import</a><br/>Branch GIT ID: <a href="https://github.com/gustavolimav/liferay-portal/commit/f4fd2bfd77a12ddaa77297b7ea280d73930ac125">f4fd2bfd77a12ddaa77297b7ea280d73930ac125</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-12.liferay.com/job/test-portal-source-format/4699/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-12.liferay.com/userContent/jobs/test-portal-source-format/builds/4699/jenkins-report.html">here</a>.</h5></details></html>

2023-02-09 12:53 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-12.liferay.com/job/test-portal-source-format/4699/">test-portal-source-format#4699</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-12.liferay.com/userContent/jobs/test-portal-source-format/builds/4699/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-search/liferay-portal/pull/783">liferay-search#783</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2191193736">[master] ci:test:sf - gustavolimav &gt; liferay-search - PR#783 - 2023-02-09[04:43:05]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-12.liferay.com/job/publish-testray-report/3127/">publish-testray-report#3127</a><br/></div></div>

2023-02-09 14:02 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest(master)/6280/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/6280/jenkins-report.html">here</a>.</b></p>

2023-02-09 14:20 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>search</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest(master)/2817/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-33.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/2817/jenkins-report.html">here</a>.</b></p>

2023-02-09 14:20 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-6.liferay.com/job/test-portal-source-format/6305/">test-portal-source-format#6305</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-6.liferay.com/userContent/jobs/test-portal-source-format/builds/6305/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-search/liferay-portal/pull/783">liferay-search#783</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2191257731">[master] ci:test:sf - gustavolimav &gt; liferay-search - PR#783 - 2023-02-09[04:33:45]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-6.liferay.com/job/publish-testray-report/3684/">publish-testray-report#3684</a><br/></div></div>

2023-02-09 18:24 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:search - 134 out of 153 jobs passed in 4 hours 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/b38777bdf00d43dcb9d978655717a3c5886179e1">b38777bdf00d43dcb9d978655717a3c5886179e1</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/b38777bdf00d43dcb9d978655717a3c5886179e1">b38777bdf00d43dcb9d978655717a3c5886179e1</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2190921451">EE Development Acceptance (master) - 4269 - 2023-02-08[20:27:01]</a></p><details><summary><strong>ci:test:search - 134 out of 153 jobs PASSED</strong></summary><div><h4>19 Failed Jobs:</h4><ul><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest(master)/2817/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>central-requirements-jdk8<ul><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/350954/">central-requirements-jdk8/0/0</a></li></ul></li><li>functional-tomcat90-mysql57-jdk11_open<ul><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/160533/">functional-tomcat90-mysql57-jdk11_open/0/0</a></li><li><a href="https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/151147/">functional-tomcat90-mysql57-jdk11_open/0/1</a></li></ul></li><li>functional-tomcat90-mysql57-jdk8<ul><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/384904/">functional-tomcat90-mysql57-jdk8/0/0</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/460280/">functional-tomcat90-mysql57-jdk8/0/1</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/374677/">functional-tomcat90-mysql57-jdk8/0/2</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/416378/">functional-tomcat90-mysql57-jdk8/0/3</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/378243/">functional-tomcat90-mysql57-jdk8/0/4</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/256805/">functional-tomcat90-mysql57-jdk8/0/5</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/378242/">functional-tomcat90-mysql57-jdk8/0/6</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/439168/">functional-tomcat90-mysql57-jdk8/0/7</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/350952/">functional-tomcat90-mysql57-jdk8/0/8</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/404341/">functional-tomcat90-mysql57-jdk8/0/9</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/460276/">functional-tomcat90-mysql57-jdk8/0/10</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/417403/">functional-tomcat90-mysql57-jdk8/1/0</a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/165360/">functional-tomcat90-mysql57-jdk8/1/1</a></li><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/157018/">functional-tomcat90-mysql57-jdk8/1/2</a></li><li><a href="https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/151992/">functional-tomcat90-mysql57-jdk8/1/3</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/460277/">functional-tomcat90-mysql57-jdk8/1/4</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/374674/">functional-tomcat90-mysql57-jdk8/1/5</a></li><li><a href="https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/146820/">functional-tomcat90-mysql57-jdk8/1/6</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/374675/">functional-tomcat90-mysql57-jdk8/1/7</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/384902/">functional-tomcat90-mysql57-jdk8/1/8</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/417404/">functional-tomcat90-mysql57-jdk8/1/9</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/460284/">functional-tomcat90-mysql57-jdk8/1/10</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/374679/">functional-tomcat90-mysql57-jdk8/1/11</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/348318/">functional-tomcat90-mysql57-jdk8/1/12</a></li><li><a href="https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/159283/">functional-tomcat90-mysql57-jdk8/1/13</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/432796/">functional-tomcat90-mysql57-jdk8/1/14</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/460285/">functional-tomcat90-mysql57-jdk8/1/15</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/215456/">functional-tomcat90-mysql57-jdk8/1/16</a></li><li><a href="https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/158308/">functional-tomcat90-mysql57-jdk8/1/17</a></li><li><a href="https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/151994/">functional-tomcat90-mysql57-jdk8/1/18</a></li><li><a href="https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/140015/">functional-tomcat90-mysql57-jdk8/1/19</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/256806/">functional-tomcat90-mysql57-jdk8/1/20</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/215453/">functional-tomcat90-mysql57-jdk8/1/21</a></li><li><a href="https://test-1-18.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/162520/">functional-tomcat90-mysql57-jdk8/1/22</a></li><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/157020/">functional-tomcat90-mysql57-jdk8/1/23</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/439169/">functional-tomcat90-mysql57-jdk8/1/24</a></li><li><a href="https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/151995/">functional-tomcat90-mysql57-jdk8/2/0</a></li><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/145963/">functional-tomcat90-mysql57-jdk8/2/1</a></li><li><a href="https://test-1-12.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/165667/">functional-tomcat90-mysql57-jdk8/2/2</a></li><li><a href="https://test-1-15.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/160611/"><strike>functional-tomcat90-mysql57-jdk8/2/3</strike></a></li><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-downstrea [...]

2023-02-09 18:35 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest(master)/2817/">test-portal-acceptance-pullrequest(master)#2817</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-33.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/2817/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>search<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-search/liferay-portal/pull/783">liferay-search#783</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2191366487">[master] ci:test:search - gustavolimav &gt; liferay-search - PR#783 - 2023-02-09[06:20:11]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-33.liferay.com/job/publish-testray-report/6619/">publish-testray-report#6619</a><br/></div></div>

2023-02-09 20:00 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:stable - 28 out of 28 jobs passed</h3><h3>:x: ci:test:relevant - 114 out of 119 jobs passed in 5 hours 59 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/b38777bdf00d43dcb9d978655717a3c5886179e1">b38777bdf00d43dcb9d978655717a3c5886179e1</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/b38777bdf00d43dcb9d978655717a3c5886179e1">b38777bdf00d43dcb9d978655717a3c5886179e1</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2190921451">EE Development Acceptance (master) - 4269 - 2023-02-08[20:27:01]</a></p><details><summary><strong>ci:test:stable - 28 out of 28 jobs PASSED</strong></summary><details><summary><strong>28 Successful Jobs:</strong></summary><ul/></details></details><details><summary><strong>ci:test:relevant - 114 out of 119 jobs PASSED</strong></summary><div><h4>5 Failed Jobs:</h4><ul><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest(master)/6280/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>central-requirements-jdk8<ul><li><a href="https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/140004/">central-requirements-jdk8/0/0</a></li></ul></li><li>empty-osgi-core-dir-jdk8<ul><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/165344/">empty-osgi-core-dir-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57-jdk11_open<ul><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/348275/">functional-smoke-tomcat90-mysql57-jdk11_open/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57-jdk8_stable<ul><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/404310/">functional-smoke-tomcat90-mysql57-jdk8_stable/0/0</a></li></ul></li><li>functional-smoke-wildfly180-mariadb104-jdk8<ul><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/416345/">functional-smoke-wildfly180-mariadb104-jdk8/0/0</a></li></ul></li><li>functional-smoke-wildfly180-mariadb106-jdk8<ul><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/348273/">functional-smoke-wildfly180-mariadb106-jdk8/0/0</a></li></ul></li><li>functional-tomcat90-mysql57-chrome100-jdk8<ul><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/256782/">functional-tomcat90-mysql57-chrome100-jdk8/0/0</a></li><li><a href="https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/151136/">functional-tomcat90-mysql57-chrome100-jdk8/0/1</a></li><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/145951/">functional-tomcat90-mysql57-chrome100-jdk8/0/2</a></li><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/157009/">functional-tomcat90-mysql57-chrome100-jdk8/0/3</a></li><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/160519/">functional-tomcat90-mysql57-chrome100-jdk8/0/4</a></li><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/160518/">functional-tomcat90-mysql57-chrome100-jdk8/0/5</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/350927/">functional-tomcat90-mysql57-chrome100-jdk8/0/6</a></li><li><a href="https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/151977/">functional-tomcat90-mysql57-chrome100-jdk8/0/7</a></li><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/165110/">functional-tomcat90-mysql57-chrome100-jdk8/0/8</a></li><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/150848/">functional-tomcat90-mysql57-chrome100-jdk8/0/9</a></li><li><a href="https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/151978/">functional-tomcat90-mysql57-chrome100-jdk8/0/10</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/350929/">functional-tomcat90-mysql57-chrome100-jdk8/0/11</a></li><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/150849/">functional-tomcat90-mysql57-chrome100-jdk8/0/12</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/384874/">functional-tomcat90-mysql57-chrome100-jdk8/0/13</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/403249/">functional-tomcat90-mysql57-chrome100-jdk8/0/14</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/416344/">functional-tomcat90-mysql57-chrome100-jdk8/0/15</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/350930/">functional-tomcat90-mysql57-chrome100-jdk8/0/16</a></li><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/151499/">functional-tomcat90-mysql57-chrome100-jdk8/0/17</a></li><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/165111/">functional-tomcat90-mysql57-chrome100-jdk8/0/18</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/256783/">functional-tomcat90-mysql57-chrome100-jdk8/0/19</a></li><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/157008/">functional-tomcat90-mysql57-chrome100-jdk8/0/20</a></li><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/150847/">functional-tomcat90-mysql57-chrome100-jdk8/0/21</a></li><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/145949/">functional-tomcat90-mysql57-chrome100-jdk8/0/22</a></li><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/157007/">functional-tomcat90-mysql57-chrome100-jdk8/0/23</a></li><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/145950/">functional-tomcat90-mysql57-chrome100-jdk8/0/24</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/439124/">functional-tomcat90-mysql57-chrome100-jdk8/1/0</a></li></ul></li><li>functional-upgrade-tomcat90-mysql57-jdk8<ul><li><a href="https://test-1-18.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/162504/">functional-upgrade-tomcat90-mysql57-jdk8/0/0</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/404309/">functional-upgrade-tomcat90-mysql57-jdk8/0/1</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/215414/">functional-upgrade-tomcat90-mysql57-jdk8/0/2</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/439127/">functional-upgrade-tomcat90-mysql57-jdk8/0/3</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/416343/">functional-upgrade-tomcat90-mysql57-jdk8/0/4</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/378208/">functional-upgrade-tomcat90-mysql57-jdk8/0/5</a></li><li><a  [...]

2023-02-09 20:05 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest(master)/6280/">test-portal-acceptance-pullrequest(master)#6280</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/6280/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-search/liferay-portal/pull/783">liferay-search#783</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2191484230">[master] ci:test:relevant - gustavolimav &gt; liferay-search - PR#783 - 2023-02-09[06:01:43]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-38.liferay.com/job/publish-testray-report/13767/">publish-testray-report#13767</a><br/></div></div>

2023-02-10 12:23 UTC, gustavolimav commented
ci:test:sf

2023-02-10 12:23 UTC, gustavolimav commented
ci:test:sf

2023-02-10 12:24 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-35.liferay.com/job/test-portal-source-format/2066/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-35.liferay.com/userContent/jobs/test-portal-source-format/builds/2066/jenkins-report.html">here</a>.</b></p>

2023-02-10 12:25 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-31.liferay.com/job/test-portal-source-format/4691/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-source-format/builds/4691/jenkins-report.html">here</a>.</b></p>

2023-02-10 12:26 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/ae403c678eca01bfcf819db7b9b156d1f1cdd957">ae403c678eca01bfcf819db7b9b156d1f1cdd957</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/gustavolimav/liferay-portal/tree/LPS-171159_blueprint_element_export_import">LPS-171159_blueprint_element_export_import</a><br/>Branch GIT ID: <a href="https://github.com/gustavolimav/liferay-portal/commit/6eb6ef81b915923bb2263f4eec8b2f1721b892fc">6eb6ef81b915923bb2263f4eec8b2f1721b892fc</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-35.liferay.com/job/test-portal-source-format/2066/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-35.liferay.com/userContent/jobs/test-portal-source-format/builds/2066/jenkins-report.html">here</a>.</h5></details></html>

2023-02-10 12:27 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/ae403c678eca01bfcf819db7b9b156d1f1cdd957">ae403c678eca01bfcf819db7b9b156d1f1cdd957</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/gustavolimav/liferay-portal/tree/LPS-171159_blueprint_element_export_import">LPS-171159_blueprint_element_export_import</a><br/>Branch GIT ID: <a href="https://github.com/gustavolimav/liferay-portal/commit/6eb6ef81b915923bb2263f4eec8b2f1721b892fc">6eb6ef81b915923bb2263f4eec8b2f1721b892fc</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-31.liferay.com/job/test-portal-source-format/4691/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-source-format/builds/4691/jenkins-report.html">here</a>.</h5></details></html>

2023-02-10 12:28 UTC, gustavolimav commented
ci:test:relevant

2023-02-10 12:29 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest(master)/7587/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/7587/jenkins-report.html">here</a>.</b></p>

2023-02-10 12:29 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>search</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest(master)/8868/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/8868/jenkins-report.html">here</a>.</b></p>

2023-02-10 12:29 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-35.liferay.com/job/test-portal-source-format/2066/">test-portal-source-format#2066</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-35.liferay.com/userContent/jobs/test-portal-source-format/builds/2066/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-search/liferay-portal/pull/783">liferay-search#783</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2192721728">[master] ci:test:sf - gustavolimav &gt; liferay-search - PR#783 - 2023-02-10[04:23:20]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-35.liferay.com/job/publish-testray-report/8184/">publish-testray-report#8184</a><br/></div></div>

2023-02-10 12:30 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-31.liferay.com/job/test-portal-source-format/4691/">test-portal-source-format#4691</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-source-format/builds/4691/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-search/liferay-portal/pull/783">liferay-search#783</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2192721783">[master] ci:test:sf - gustavolimav &gt; liferay-search - PR#783 - 2023-02-10[04:23:28]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-31.liferay.com/job/publish-testray-report/17412/">publish-testray-report#17412</a><br/></div></div>

2023-02-10 15:47 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:search - 114 out of 146 jobs passed in 3 hours 18 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/ae403c678eca01bfcf819db7b9b156d1f1cdd957">ae403c678eca01bfcf819db7b9b156d1f1cdd957</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/5ea9b45ce0a06e5eb00ae03732bd3445dff2bc7a">5ea9b45ce0a06e5eb00ae03732bd3445dff2bc7a</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2192670741">EE Development Acceptance (master) - 4271 - 2023-02-10[00:06:26]</a></p><details><summary><strong>ci:test:search - 114 out of 146 jobs PASSED</strong></summary><div><h4>32 Failed Jobs:</h4><ul><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest(master)/8868/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>central-requirements-jdk8<ul><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/376927/">central-requirements-jdk8/0/0</a></li></ul></li><li>functional-tomcat90-mysql57-jdk11_open<ul><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/380594/">functional-tomcat90-mysql57-jdk11_open/0/0</a></li><li><a href="https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/151970/">functional-tomcat90-mysql57-jdk11_open/0/1</a></li></ul></li><li>functional-tomcat90-mysql57-jdk8<ul><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/218049/"><strike>functional-tomcat90-mysql57-jdk8/0/0</strike></a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/380597/"><strike>functional-tomcat90-mysql57-jdk8/0/1</strike></a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/463015/"><strike>functional-tomcat90-mysql57-jdk8/0/2</strike></a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/350519/"><strike>functional-tomcat90-mysql57-jdk8/0/3</strike></a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/441831/"><strike>functional-tomcat90-mysql57-jdk8/0/4</strike></a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/418653/"><strike>functional-tomcat90-mysql57-jdk8/0/5</strike></a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/418652/"><strike>functional-tomcat90-mysql57-jdk8/0/6</strike></a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/441832/">functional-tomcat90-mysql57-jdk8/0/7</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/418654/">functional-tomcat90-mysql57-jdk8/0/8</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/350520/"><strike>functional-tomcat90-mysql57-jdk8/0/9</strike></a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/406457/">functional-tomcat90-mysql57-jdk8/0/10</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/405468/">functional-tomcat90-mysql57-jdk8/1/0</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/218045/">functional-tomcat90-mysql57-jdk8/1/1</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/380595/">functional-tomcat90-mysql57-jdk8/1/2</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/376923/"><strike>functional-tomcat90-mysql57-jdk8/1/3</strike></a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/352487/">functional-tomcat90-mysql57-jdk8/1/4</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/419876/">functional-tomcat90-mysql57-jdk8/1/5</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/376924/">functional-tomcat90-mysql57-jdk8/1/6</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/258374/">functional-tomcat90-mysql57-jdk8/1/7</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/435089/">functional-tomcat90-mysql57-jdk8/1/8</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/405469/">functional-tomcat90-mysql57-jdk8/1/9</a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/166359/"><strike>functional-tomcat90-mysql57-jdk8/1/10</strike></a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/406460/"><strike>functional-tomcat90-mysql57-jdk8/1/11</strike></a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/386109/">functional-tomcat90-mysql57-jdk8/1/12</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/463018/">functional-tomcat90-mysql57-jdk8/1/13</a></li><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/157875/">functional-tomcat90-mysql57-jdk8/1/14</a></li><li><a href="https://test-1-15.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/161421/">functional-tomcat90-mysql57-jdk8/1/15</a></li><li><a href="https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/136857/">functional-tomcat90-mysql57-jdk8/1/16</a></li><li><a href="https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/162954/">functional-tomcat90-mysql57-jdk8/1/17</a></li><li><a href="https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/147657/">functional-tomcat90-mysql57-jdk8/1/18</a></li><li><a href="https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/162955/">functional-tomcat90-mysql57-jdk8/1/19</a></li><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/151826/">functional-tomcat90-mysql57-jdk8/1/20</a></li><li><a href="https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/151973/">functional-tomcat90-mysql57-jdk8/1/21</a></li><li><a href="https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/147658/">functional-tomcat90-mysql57-jdk8/1/22</a></li><li><a href="https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/136856/">functional-tomcat90-mysql57-jdk8/1/23</a></li><li><a href="https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/153036/"><strike>functional-tomcat90-mysql57-jdk8/1/24</strike></a></li><li><a href="https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/160187/"><strike>functional-tomcat90-mysql57-jdk8/2/0</strike></a></li><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/166010/">functional-tomcat90-mysql57-jdk8/2/1</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/405473/"><strike>functional-tomcat90-mysql57-jdk8/2/2</strike></a></li><li><a href="https:/ [...]

2023-02-10 15:57 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest(master)/8868/">test-portal-acceptance-pullrequest(master)#8868</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/8868/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>search<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-search/liferay-portal/pull/783">liferay-search#783</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2192869492">[master] ci:test:search - gustavolimav &gt; liferay-search - PR#783 - 2023-02-10[04:28:53]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-37.liferay.com/job/publish-testray-report/20069/">publish-testray-report#20069</a><br/></div></div>

2023-02-10 16:27 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:stable - 27 out of 28 jobs passed</h3><h3>:x: ci:test:relevant - 108 out of 119 jobs passed in 3 hours 58 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/ae403c678eca01bfcf819db7b9b156d1f1cdd957">ae403c678eca01bfcf819db7b9b156d1f1cdd957</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/5ea9b45ce0a06e5eb00ae03732bd3445dff2bc7a">5ea9b45ce0a06e5eb00ae03732bd3445dff2bc7a</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2192670741">EE Development Acceptance (master) - 4271 - 2023-02-10[00:06:26]</a></p><details><summary><strong>ci:test:stable - 27 out of 28 jobs PASSED</strong></summary><div><h4>1 Failed Jobs:</h4><ul><li>central-requirements-jdk8<ul><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/418642/">central-requirements-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57-jdk8_stable<ul><li><a href="https://test-1-12.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/166478/">functional-smoke-tomcat90-mysql57-jdk8_stable/0/0</a></li></ul></li><li>functional-upgrade-tomcat90-mysql57-jdk8_stable<ul><li><a href="https://test-1-12.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/166475/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/0</a></li><li><a href="https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/147648/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/1</a></li></ul></li><li>js-unit-jdk8<ul><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/352476/">js-unit-jdk8/0/0</a></li></ul></li><li>modules-compile-jdk8<ul><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/386105/">modules-compile-jdk8/0/0</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/419864/">modules-compile-jdk8/0/1</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/350505/">modules-compile-jdk8/0/2</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/376910/">modules-compile-jdk8/0/3</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/462998/">modules-compile-jdk8/0/4</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/419865/">modules-compile-jdk8/0/5</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/406439/">modules-compile-jdk8/0/6</a></li><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/157870/">modules-compile-jdk8/0/7</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/435075/">modules-compile-jdk8/0/8</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/405453/">modules-compile-jdk8/0/9</a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/166351/">modules-compile-jdk8/0/10</a></li><li><a href="https://test-1-18.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/163372/">modules-compile-jdk8/0/11</a></li><li><a href="https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/159095/">modules-compile-jdk8/0/12</a></li><li><a href="https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/136846/">modules-compile-jdk8/0/13</a></li></ul></li><li>modules-integration-mysql57-jdk8_stable<ul><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/350502/">modules-integration-mysql57-jdk8_stable/0/0</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/376907/">modules-integration-mysql57-jdk8_stable/0/1</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/380580/">modules-integration-mysql57-jdk8_stable/0/2</a></li></ul></li><li>modules-unit-jdk8_stable<ul><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/151816/">modules-unit-jdk8_stable/0/0</a></li></ul></li><li>pmd-jdk8<ul><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/406438/">pmd-jdk8/0/0</a></li></ul></li><li>portal-license-smoke-jdk8<ul><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/441813/"><strike>portal-license-smoke-jdk8/0/0</strike></a></li></ul></li><li>rest-builder-jdk8<ul><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/166006/">rest-builder-jdk8/0/0</a></li></ul></li><li>service-builder-jdk8<ul><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/405455/">service-builder-jdk8/0/0</a></li></ul></li><li>unit-jdk8_stable<ul><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/406440/">unit-jdk8_stable/0/0</a></li></ul></li></ul></div><details><summary><strong>27 Successful Jobs:</strong></summary><ul/></details></details><details><summary><strong>ci:test:relevant - 108 out of 119 jobs PASSED</strong></summary><div><h4>11 Failed Jobs:</h4><ul><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest(master)/7587/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>central-requirements-jdk8<ul><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/418642/">central-requirements-jdk8/0/0</a></li></ul></li><li>empty-osgi-core-dir-jdk8<ul><li><a href="https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/147650/">empty-osgi-core-dir-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57-jdk11_open<ul><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/441814/">functional-smoke-tomcat90-mysql57-jdk11_open/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57-jdk8_stable<ul><li><a href="https://test-1-12.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/166478/">functional-smoke-tomcat90-mysql57-jdk8_stable/0/0</a></li></ul></li><li>functional-smoke-wildfly180-mariadb104-jdk8<ul><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/462997/">functional-smoke-wildfly180-mariadb104-jdk8/0/0</a></li></ul></li><li>functional-smoke-wildfly180-mariadb106-jdk8<ul><li><a href="https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/136845/">functional-smoke-wildfly180-mariadb106-jdk8/0/0</a></li></ul></li><li>functional-tomcat90-mysql57-chrome100-jdk8<ul><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/387962/">functional-tomcat90-mysql57-chrome100-jdk8/0/0</a></li><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/161392/"><strike>functional-tomcat90-mysql57-chrome100-jdk8/0/1</strike></a></li><li><a href="https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/147649/">functional-tomcat90-mysql57-chrome100-jdk8/0/2</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/419862/">functional-tomcat90-mysq [...]

2023-02-10 17:28 UTC, gustavolimav commented
ci:test:sf

2023-02-10 17:28 UTC, gustavolimav commented
ci:test:relevant

2023-02-10 17:29 UTC, gustavolimav commented
ci:test:search

2023-02-10 17:30 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-37.liferay.com/job/test-portal-source-format/5220/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/5220/jenkins-report.html">here</a>.</b></p>

2023-02-10 17:32 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/d48b4c356269b67c7c07fc44abf49cc4377b51b4">d48b4c356269b67c7c07fc44abf49cc4377b51b4</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/gustavolimav/liferay-portal/tree/LPS-171159_blueprint_element_export_import">LPS-171159_blueprint_element_export_import</a><br/>Branch GIT ID: <a href="https://github.com/gustavolimav/liferay-portal/commit/0ea331c4a8aec78c76758fb06b32ea27c0f2801f">0ea331c4a8aec78c76758fb06b32ea27c0f2801f</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-37.liferay.com/job/test-portal-source-format/5220/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/5220/jenkins-report.html">here</a>.</h5></details></html>

2023-02-10 17:41 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-37.liferay.com/job/test-portal-source-format/5220/">test-portal-source-format#5220</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/5220/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-search/liferay-portal/pull/783">liferay-search#783</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2192906941">[master] ci:test:sf - gustavolimav &gt; liferay-search - PR#783 - 2023-02-10[09:28:52]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-37.liferay.com/job/publish-testray-report/20079/">publish-testray-report#20079</a><br/></div></div>

2023-02-10 20:35 UTC, joshchong commented
Sent to BChan:
https://github.com/brianchandotcom/liferay-portal/pull/130108

2023-02-10 20:35 UTC, closed without merging